import { Customer, MaintenanceRecord, OSStatus, Part, ServiceOrder, Tenant, User, Vehicle } from "./types";

const nowMs = Date.now();
const dayMs = 24 * 60 * 60 * 1000;

export const SEED_TENANTS: Tenant[] = [
  {
    id: "tenant-1",
    name: "Oficina MotoShow Express",
    slug: "motoshow",
    plan: "MONTHLY",
    subscriptionCycle: "MONTHLY",
    subscriptionPrice: 280,
    subscriptionDurationDays: 30,
    subscriptionStartedAt: new Date(nowMs - 26.5 * dayMs).toISOString(),
    subscriptionExpiresAt: new Date(nowMs + 3.5 * dayMs).toISOString(), // ~3.5 dias restantes (<= 15% -> Alerta Ativo)
    subscriptionStatus: "WARNING",
    phone: "(11) 98765-4321",
    cnpj: "45.123.789/0001-90",
    address: "Av. Radial Leste, 2450 - Tatuapé, São Paulo - SP",
    createdAt: "2024-01-15T08:00:00Z",
    lastAccessAt: "2026-09-22T10:45:00Z",
    lastAccessUser: "João Silva",
    lastAccessUserRole: "Proprietário / Admin",
    totalRevenue: 18450,
    ordersCount: 24,
    vehiclesCount: 18,
    activeUsersCount: 5,
    status: "ACTIVE",
  },
  {
    id: "tenant-2",
    name: "Speed Racing Moto Center",
    slug: "speedracing",
    plan: "MONTHLY",
    subscriptionCycle: "MONTHLY",
    subscriptionPrice: 280,
    subscriptionDurationDays: 30,
    subscriptionStartedAt: new Date(nowMs - 35 * dayMs).toISOString(),
    subscriptionExpiresAt: new Date(nowMs - 5 * dayMs).toISOString(), // Venceu há 5 dias -> Vencido (Bloqueio no login)
    subscriptionStatus: "EXPIRED",
    phone: "(11) 97123-9988",
    cnpj: "32.987.654/0001-12",
    address: "Rua das Motos, 110 - Centro, Curitiba - PR",
    createdAt: "2024-02-10T10:00:00Z",
    lastAccessAt: "2026-09-22T08:20:00Z",
    lastAccessUser: "Marcos Gerente",
    lastAccessUserRole: "Gerente Geral",
    totalRevenue: 8900,
    ordersCount: 12,
    vehiclesCount: 10,
    activeUsersCount: 3,
    status: "ACTIVE",
  },
  {
    id: "tenant-3",
    name: "Náutica & Jet Marine Service",
    slug: "marineservice",
    plan: "ANNUAL",
    subscriptionCycle: "ANNUAL",
    subscriptionPrice: 2000,
    subscriptionDurationDays: 365,
    subscriptionStartedAt: new Date(nowMs - 60 * dayMs).toISOString(),
    subscriptionExpiresAt: new Date(nowMs + 305 * dayMs).toISOString(), // 305 dias restantes (Em dia)
    subscriptionStatus: "ACTIVE",
    phone: "(13) 98822-1100",
    cnpj: "19.876.543/0001-44",
    address: "Av. Portuária, 500 - Ponta da Praia, Santos - SP",
    createdAt: "2023-11-20T14:00:00Z",
    lastAccessAt: "2026-09-21T18:10:00Z",
    lastAccessUser: "Felipe Engenheiro",
    lastAccessUserRole: "Diretor Técnico",
    totalRevenue: 42300,
    ordersCount: 19,
    vehiclesCount: 14,
    activeUsersCount: 7,
    status: "ACTIVE",
  },
  {
    id: "tenant-4",
    name: "Rota 66 Custom & Oficina",
    slug: "rota66",
    plan: "ANNUAL",
    subscriptionCycle: "ANNUAL",
    subscriptionPrice: 2000,
    subscriptionDurationDays: 365,
    subscriptionStartedAt: new Date(nowMs - 325 * dayMs).toISOString(),
    subscriptionExpiresAt: new Date(nowMs + 40 * dayMs).toISOString(), // 40 dias restantes (<= 54.75 dias -> Alerta Ativo)
    subscriptionStatus: "WARNING",
    phone: "(31) 97711-4433",
    cnpj: "28.345.678/0001-88",
    address: "Av. do Contorno, 3200 - Savassi, Belo Horizonte - MG",
    createdAt: "2024-03-05T09:15:00Z",
    lastAccessAt: "2026-09-21T14:30:00Z",
    lastAccessUser: "Carla Recepção",
    lastAccessUserRole: "Recepcionista",
    totalRevenue: 14200,
    ordersCount: 16,
    vehiclesCount: 12,
    activeUsersCount: 4,
    status: "ACTIVE",
  },
];

export const SEED_USERS: User[] = [
  {
    id: "user-master",
    name: "JR Branquinho",
    email: "jrbranquinho@motoshop.com.br",
    username: "jrbranquinho",
    role: "SUPER_ADMIN",
    tenantId: "tenant-1",
    phone: "(11) 99999-8888",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-saas",
    name: "Alexandre Fundador",
    email: "admin@motoshop.com.br",
    username: "alexandre",
    role: "SUPER_ADMIN",
    tenantId: "tenant-1",
    phone: "(11) 99999-0001",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-1",
    name: "João Silva",
    email: "joao@motoshow.com.br",
    username: "joaosilva",
    role: "ADMIN",
    tenantId: "tenant-1",
    phone: "(11) 98765-4321",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-mgr",
    name: "Roberto Gerente",
    email: "roberto@motoshow.com.br",
    username: "robertogerente",
    role: "MANAGER",
    tenantId: "tenant-1",
    phone: "(11) 98111-2233",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-2",
    name: "Carlos 'Carlão' Santos",
    email: "carlao@motoshow.com.br",
    username: "carlao",
    role: "MECHANIC",
    tenantId: "tenant-1",
    phone: "(11) 97654-3210",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-3",
    name: "Ricardo Mendes",
    email: "ricardo@motoshow.com.br",
    username: "ricardo",
    role: "MECHANIC",
    tenantId: "tenant-1",
    phone: "(11) 96543-2109",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "user-4",
    name: "Paula Souza",
    email: "paula@motoshow.com.br",
    username: "paula",
    role: "RECEPTIONIST",
    tenantId: "tenant-1",
    phone: "(11) 95432-1098",
    password: "mot-os123",
    mustChangePassword: true,
    twoFactorEnabled: true,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
];


export const SEED_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    name: "Marcos Vinícius Oliveira",
    phone: "(11) 99876-5432",
    email: "marcos.oliveira@gmail.com",
    document: "123.456.789-00",
    tenantId: "tenant-1",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "cust-2",
    name: "Beatriz Alencar Santos",
    phone: "(11) 98877-6655",
    email: "beatriz.santos@outlook.com",
    document: "234.567.890-11",
    tenantId: "tenant-1",
    createdAt: "2024-03-10T14:30:00Z",
  },
  {
    id: "cust-3",
    name: "Rodrigo Ferreira",
    phone: "(11) 97766-5544",
    email: "rodrigo.motos@gmail.com",
    document: "345.678.901-22",
    tenantId: "tenant-1",
    createdAt: "2024-03-15T09:15:00Z",
  },
  {
    id: "cust-4",
    name: "Lucas Pinheiro Lima",
    phone: "(11) 96655-4433",
    email: "lucas.pinheiro@yahoo.com.br",
    document: "456.789.012-33",
    tenantId: "tenant-1",
    createdAt: "2024-04-02T11:20:00Z",
  },
  {
    id: "cust-5",
    name: "Amanda Duarte",
    phone: "(11) 95544-3322",
    email: "amanda.duarte@empresa.com",
    document: "567.890.123-44",
    tenantId: "tenant-1",
    createdAt: "2024-04-18T16:45:00Z",
  },
];

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: "veh-1",
    plate: "BRA2E19",
    brand: "Honda",
    model: "CG 160 Titan FlexOne",
    year: 2022,
    color: "Azul Metálico",
    chassis: "9C2KC2800NR123456",
    currentKm: 28450,
    customerId: "cust-1",
    tenantId: "tenant-1",
    createdAt: "2024-03-01T10:15:00Z",
  },
  {
    id: "veh-2",
    plate: "FDX4G82",
    brand: "Yamaha",
    model: "Fazer FZ25 ABS",
    year: 2023,
    color: "Vermelha Magma",
    chassis: "9C6KG0400PR654321",
    currentKm: 14200,
    customerId: "cust-2",
    tenantId: "tenant-1",
    createdAt: "2024-03-10T14:40:00Z",
  },
  {
    id: "veh-3",
    plate: "MOT9921",
    brand: "Honda",
    model: "Biz 125 ES",
    year: 2020,
    color: "Branca Perolizada",
    chassis: "9C2JC4800LR789012",
    currentKm: 38100,
    customerId: "cust-3",
    tenantId: "tenant-1",
    createdAt: "2024-03-15T09:30:00Z",
  },
  {
    id: "veh-4",
    plate: "RAC3C40",
    brand: "Yamaha",
    model: "MT-07 ABS",
    year: 2021,
    color: "Storm Fluo (Preta e Cyan)",
    chassis: "9C6RM1700MR345678",
    currentKm: 22800,
    customerId: "cust-4",
    tenantId: "tenant-1",
    createdAt: "2024-04-02T11:40:00Z",
  },
  {
    id: "veh-5",
    plate: "BMW8H15",
    brand: "BMW",
    model: "G 310 GS Adventure",
    year: 2024,
    color: "Cinza Kallen / Vermelha",
    chassis: "WB10G3105R9012345",
    currentKm: 6900,
    customerId: "cust-5",
    tenantId: "tenant-1",
    createdAt: "2024-04-18T17:00:00Z",
  },
];

export const SEED_PARTS: Part[] = [
  {
    id: "part-1",
    code: "LUB-001",
    name: "Óleo Motor Motul 10W30 4T 3000 Mineral (1L)",
    description: "Óleo lubrificante mineral genuíno recomendado para Honda CG 160 e Biz",
    brand: "Motul",
    category: "Lubrificantes",
    costPrice: 24.5,
    salePrice: 42.0,
    stockQty: 34,
    minStock: 10,
    location: "Prateleira A1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-2",
    code: "LUB-002",
    name: "Óleo Motor Motul 5100 10W40 Semissintético (1L)",
    description: "Óleo semissintético de alta performance para Yamaha Fazer e MT",
    brand: "Motul",
    category: "Lubrificantes",
    costPrice: 38.0,
    salePrice: 65.0,
    stockQty: 18,
    minStock: 8,
    location: "Prateleira A2",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-3",
    code: "FRE-001",
    name: "Pastilha de Freio Dianteira Cobreq Street N-944",
    description: "Pastilha orgânica para CG 160 Titan / Fan ESD",
    brand: "Cobreq",
    category: "Freios",
    costPrice: 19.8,
    salePrice: 38.0,
    stockQty: 12,
    minStock: 5,
    location: "Gaveteiro B3",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-4",
    code: "FRE-002",
    name: "Pastilha de Freio Traseira Cobreq N-945",
    description: "Pastilha traseira de freio para Fazer 250 / MT-03",
    brand: "Cobreq",
    category: "Freios",
    costPrice: 22.0,
    salePrice: 44.0,
    stockQty: 3, // ESTOQUE BAIXO!
    minStock: 6,
    location: "Gaveteiro B4",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-5",
    code: "FRE-003",
    name: "Lona de Freio Traseira Diafrag Standard",
    description: "Sapata de freio traseiro p/ Honda CG / Titan / Biz",
    brand: "Diafrag",
    category: "Freios",
    costPrice: 14.0,
    salePrice: 28.0,
    stockQty: 15,
    minStock: 6,
    location: "Gaveteiro B1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-6",
    code: "IGN-001",
    name: "Vela de Ignição NGK CPR8EA-9",
    description: "Vela de ignição original Honda CG 160 / Biz 125",
    brand: "NGK",
    category: "Elétrica & Ignição",
    costPrice: 16.5,
    salePrice: 32.0,
    stockQty: 24,
    minStock: 8,
    location: "Prateleira C1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-7",
    code: "TRA-001",
    name: "Kit Transmissão D.I.D Aço 1045 c/ Retentor (CG 160)",
    description: "Coroa 44T, Pinhão 15T e Corrente 428VX DID Japonesa",
    brand: "D.I.D",
    category: "Transmissão",
    costPrice: 115.0,
    salePrice: 195.0,
    stockQty: 7,
    minStock: 4,
    location: "Prateleira D2",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-8",
    code: "TRA-002",
    name: "Kit Transmissão KMC Gold c/ Retentor (Fazer 250)",
    description: "Coroa 46T, Pinhão 15T e Corrente 428UO reforçada",
    brand: "KMC",
    category: "Transmissão",
    costPrice: 140.0,
    salePrice: 245.0,
    stockQty: 2, // ESTOQUE BAIXO!
    minStock: 4,
    location: "Prateleira D3",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-9",
    code: "PNE-001",
    name: "Pneu Traseiro Michelin City Pro 90/90-18 Tubeless",
    description: "Pneu anti-furo ultra durável para linha Honda 160 / Fan",
    brand: "Michelin",
    category: "Pneus & Câmaras",
    costPrice: 185.0,
    salePrice: 290.0,
    stockQty: 6,
    minStock: 4,
    location: "Rack de Pneus P1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-10",
    code: "PNE-002",
    name: "Pneu Dianteiro Michelin City Pro 80/100-18",
    description: "Pneu dianteiro de excelente aderência no molhado",
    brand: "Michelin",
    category: "Pneus & Câmaras",
    costPrice: 160.0,
    salePrice: 250.0,
    stockQty: 5,
    minStock: 3,
    location: "Rack de Pneus P2",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-11",
    code: "FLT-001",
    name: "Filtro de Ar Condor CG 160",
    description: "Elemento filtrante de celulose sintética de alta vazão",
    brand: "Condor",
    category: "Filtros",
    costPrice: 12.0,
    salePrice: 26.0,
    stockQty: 14,
    minStock: 5,
    location: "Prateleira E1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-12",
    code: "FLT-002",
    name: "Filtro de Óleo Fram CH6015 (Fazer / Lander / MT-03)",
    description: "Filtro blindado de micropartículas metálicas",
    brand: "Fram",
    category: "Filtros",
    costPrice: 15.0,
    salePrice: 32.0,
    stockQty: 11,
    minStock: 5,
    location: "Prateleira E2",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-13",
    code: "CAB-001",
    name: "Cabo de Embreagem Allen Reforçado CG 160",
    description: "Cabo de aço inox com revestimento de Teflon anti-fricção",
    brand: "Allen",
    category: "Cabos & Comandos",
    costPrice: 14.5,
    salePrice: 29.0,
    stockQty: 8,
    minStock: 4,
    location: "Gaveteiro C3",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-14",
    code: "BAT-001",
    name: "Bateria Selada Moura MA5-D 12V 5Ah AGM",
    description: "Bateria original livre de manutenção para Titan / Fan / Factor",
    brand: "Moura",
    category: "Elétrica & Ignição",
    costPrice: 135.0,
    salePrice: 220.0,
    stockQty: 4,
    minStock: 3,
    location: "Bancada Elétrica B2",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-15",
    code: "QUI-001",
    name: "Fluido de Freio DOT 4 Motul Brake Fluid (500ml)",
    description: "Fluido para sistemas hidráulicos de alta temperatura",
    brand: "Motul",
    category: "Lubrificantes",
    costPrice: 22.0,
    salePrice: 40.0,
    stockQty: 10,
    minStock: 5,
    location: "Prateleira A3",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-16",
    code: "QUI-002",
    name: "Spray Lubrificante Corrente Motul Chain Lube Road C2",
    description: "Lubrificante especial incolor para correntes de moto",
    brand: "Motul",
    category: "Químicos & Sprays",
    costPrice: 32.0,
    salePrice: 55.0,
    stockQty: 16,
    minStock: 5,
    location: "Prateleira A4",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-17",
    code: "ROL-001",
    name: "Kit Rolamentos Roda Dianteira Nachi 6301-2RS (Par)",
    description: "Rolamentos blindados de altíssima precisão japonesa",
    brand: "Nachi",
    category: "Rolamentos & Suspensão",
    costPrice: 28.0,
    salePrice: 52.0,
    stockQty: 9,
    minStock: 4,
    location: "Gaveteiro D1",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "part-18",
    code: "AMP-001",
    name: "Lâmpada Farol LED H4 Philips Ultinon 6000K",
    description: "Lâmpada Super Branca para máxima visibilidade noturna",
    brand: "Philips",
    category: "Elétrica & Ignição",
    costPrice: 65.0,
    salePrice: 120.0,
    stockQty: 1, // ESTOQUE BAIXO CRÍTICO!
    minStock: 4,
    location: "Gaveteiro C4",
    tenantId: "tenant-1",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

export const SEED_SERVICE_ORDERS: ServiceOrder[] = [
  {
    id: "os-101",
    osNumber: 101,
    status: "IN_PROGRESS",
    vehicleId: "veh-1",
    mechanicId: "user-2", // Carlão
    tenantId: "tenant-1",
    kmAtService: 28450,
    kmNextService: 31450,
    complaint: "Moto falhando em retomadas, barulho metálico na transmissão e freio dianteiro borrachudo.",
    diagnosis: "Corrente com elos presos e desgaste excessivo na coroa. Pastilha dianteira no limite do ferro. Óleo escuro.",
    notes: "Cliente solicitou entrega até as 17h. Utilizar peças de primeira linha.",
    checklist: [
      { id: "c1", label: "Nível de combustível (1/2 tanque)", checked: true },
      { id: "c2", label: "Arranhões no escapamento e manete direito", checked: true, notes: "Queda antiga relatada" },
      { id: "c3", label: "Espelhos retrovisores íntegros", checked: true },
      { id: "c4", label: "Bateria e parte elétrica testada", checked: true },
    ],
    items: [
      {
        id: "item-1",
        serviceOrderId: "os-101",
        type: "PART",
        partId: "part-1",
        description: "Óleo Motor Motul 10W30 4T 3000 Mineral (1L)",
        quantity: 1,
        unitPrice: 42.0,
        discount: 0,
        total: 42.0,
      },
      {
        id: "item-2",
        serviceOrderId: "os-101",
        type: "PART",
        partId: "part-3",
        description: "Pastilha de Freio Dianteira Cobreq Street N-944",
        quantity: 1,
        unitPrice: 38.0,
        discount: 0,
        total: 38.0,
      },
      {
        id: "item-3",
        serviceOrderId: "os-101",
        type: "PART",
        partId: "part-7",
        description: "Kit Transmissão D.I.D Aço 1045 c/ Retentor (CG 160)",
        quantity: 1,
        unitPrice: 195.0,
        discount: 10.0,
        total: 185.0,
      },
      {
        id: "item-4",
        serviceOrderId: "os-101",
        type: "LABOR",
        description: "Mão de obra: Troca de relação, pastilha de freio dianteira e sangria",
        quantity: 1,
        unitPrice: 90.0,
        discount: 0,
        total: 90.0,
      },
    ],
    totalParts: 265.0,
    totalLabor: 90.0,
    totalDiscount: 10.0,
    totalAmount: 355.0,
    estimatedMinutes: 90,
    spentMinutes: 45,
    isTimerRunning: true,
    timerStartedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    createdAt: "2026-09-22T08:15:00Z",
    updatedAt: "2026-09-22T08:30:00Z",
  },
  {
    id: "os-102",
    osNumber: 102,
    status: "OPEN",
    vehicleId: "veh-2",
    mechanicId: "user-3", // Ricardo
    tenantId: "tenant-1",
    kmAtService: 14200,
    kmNextService: 19200,
    complaint: "Revisão geral dos 15.000 km e troca preventiva de fluidos.",
    diagnosis: "Necessária troca de óleo Motul 5100, filtro de óleo e inspeção geral de cabos e velas.",
    notes: "Cliente aguarda na recepção.",
    checklist: [
      { id: "c1", label: "Nível de combustível cheio", checked: true },
      { id: "c2", label: "Pintura sem riscos aparentes", checked: true },
      { id: "c3", label: "Farol e setas funcionando 100%", checked: true },
    ],
    items: [
      {
        id: "item-5",
        serviceOrderId: "os-102",
        type: "PART",
        partId: "part-2",
        description: "Óleo Motor Motul 5100 10W40 Semissintético (1L)",
        quantity: 1.5,
        unitPrice: 65.0,
        discount: 0,
        total: 97.5,
      },
      {
        id: "item-6",
        serviceOrderId: "os-102",
        type: "PART",
        partId: "part-12",
        description: "Filtro de Óleo Fram CH6015",
        quantity: 1,
        unitPrice: 32.0,
        discount: 0,
        total: 32.0,
      },
      {
        id: "item-7",
        serviceOrderId: "os-102",
        type: "LABOR",
        description: "Revisão programada de 15.000 km + lubrificação geral",
        quantity: 1,
        unitPrice: 120.0,
        discount: 0,
        total: 120.0,
      },
    ],
    totalParts: 129.5,
    totalLabor: 120.0,
    totalDiscount: 0,
    totalAmount: 249.5,
    estimatedMinutes: 60,
    spentMinutes: 0,
    isTimerRunning: false,
    createdAt: "2026-09-22T09:00:00Z",
    updatedAt: "2026-09-22T09:05:00Z",
  },
  {
    id: "os-103",
    osNumber: 103,
    status: "WAITING_APPROVAL",
    vehicleId: "veh-3",
    mechanicId: "user-2",
    tenantId: "tenant-1",
    kmAtService: 38100,
    kmNextService: 41000,
    complaint: "Pneu traseiro careca, moto sem arranque no botão.",
    diagnosis: "Bateria em curto (não segurando carga) e pneu traseiro no TWI com risco de multa.",
    notes: "Orçamento enviado no WhatsApp da cliente, aguardando ok.",
    checklist: [
      { id: "c1", label: "Carenagem frontal com pequenas marcas", checked: true },
      { id: "c2", label: "Freio dianteiro e traseiro operantes", checked: true },
    ],
    items: [
      {
        id: "item-8",
        serviceOrderId: "os-103",
        type: "PART",
        partId: "part-14",
        description: "Bateria Selada Moura MA5-D 12V 5Ah AGM",
        quantity: 1,
        unitPrice: 220.0,
        discount: 10.0,
        total: 210.0,
      },
      {
        id: "item-9",
        serviceOrderId: "os-103",
        type: "PART",
        partId: "part-9",
        description: "Pneu Traseiro Michelin City Pro 90/90-18 Tubeless",
        quantity: 1,
        unitPrice: 290.0,
        discount: 15.0,
        total: 275.0,
      },
      {
        id: "item-10",
        serviceOrderId: "os-103",
        type: "LABOR",
        description: "Instalação da bateria, montagem/balanceamento de pneu",
        quantity: 1,
        unitPrice: 50.0,
        discount: 0,
        total: 50.0,
      },
    ],
    totalParts: 485.0,
    totalLabor: 50.0,
    totalDiscount: 25.0,
    totalAmount: 535.0,
    estimatedMinutes: 45,
    spentMinutes: 0,
    isTimerRunning: false,
    createdAt: "2026-09-21T15:20:00Z",
    updatedAt: "2026-09-21T16:00:00Z",
  },
  {
    id: "os-104",
    osNumber: 104,
    status: "WAITING_PARTS",
    vehicleId: "veh-4",
    mechanicId: "user-3",
    tenantId: "tenant-1",
    kmAtService: 22800,
    kmNextService: 27800,
    complaint: "Luz de injeção acesa no painel e estalos na frente ao frear forte.",
    diagnosis: "Rolamentos da caixa de direção com folga e pastilha traseira totalmente gasta.",
    notes: "Aguardando chegada das pastilhas traseiras do fornecedor.",
    items: [
      {
        id: "item-11",
        serviceOrderId: "os-104",
        type: "PART",
        partId: "part-4",
        description: "Pastilha de Freio Traseira Cobreq N-945",
        quantity: 1,
        unitPrice: 44.0,
        discount: 0,
        total: 44.0,
      },
      {
        id: "item-12",
        serviceOrderId: "os-104",
        type: "LABOR",
        description: "Diagnóstico scanner OBD + Ajuste de caixa de direção",
        quantity: 1,
        unitPrice: 150.0,
        discount: 0,
        total: 150.0,
      },
    ],
    totalParts: 44.0,
    totalLabor: 150.0,
    totalDiscount: 0,
    totalAmount: 194.0,
    estimatedMinutes: 120,
    spentMinutes: 30,
    isTimerRunning: false,
    createdAt: "2026-09-21T11:00:00Z",
    updatedAt: "2026-09-21T14:10:00Z",
  },
  {
    id: "os-105",
    osNumber: 105,
    status: "COMPLETED",
    vehicleId: "veh-5",
    mechanicId: "user-2",
    tenantId: "tenant-1",
    kmAtService: 6900,
    kmNextService: 11900,
    complaint: "Primeira revisão de rodagem após viagem de 3.000 km.",
    diagnosis: "Reaperto de parafusos do chassi, troca de óleo sintético e lubrificação da corrente.",
    notes: "Moto lavada e pronta para retirada.",
    items: [
      {
        id: "item-13",
        serviceOrderId: "os-105",
        type: "PART",
        partId: "part-2",
        description: "Óleo Motor Motul 5100 10W40 Semissintético (1L)",
        quantity: 2,
        unitPrice: 65.0,
        discount: 0,
        total: 130.0,
      },
      {
        id: "item-14",
        serviceOrderId: "os-105",
        type: "PART",
        partId: "part-16",
        description: "Spray Lubrificante Corrente Motul Chain Lube Road C2",
        quantity: 1,
        unitPrice: 55.0,
        discount: 5.0,
        total: 50.0,
      },
      {
        id: "item-15",
        serviceOrderId: "os-105",
        type: "LABOR",
        description: "Revisão e regulagens BMW G 310 GS",
        quantity: 1,
        unitPrice: 180.0,
        discount: 0,
        total: 180.0,
      },
    ],
    totalParts: 180.0,
    totalLabor: 180.0,
    totalDiscount: 5.0,
    totalAmount: 355.0,
    estimatedMinutes: 60,
    spentMinutes: 55,
    isTimerRunning: false,
    completedAt: "2026-09-22T09:10:00Z",
    createdAt: "2026-09-22T07:45:00Z",
    updatedAt: "2026-09-22T09:10:00Z",
  },
];

export const SEED_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: "maint-1",
    vehicleId: "veh-1",
    km: 25000,
    description: "Troca de óleo mineral Motul 10W30 e vela NGK",
    date: "2026-06-10T14:00:00Z",
    tenantId: "tenant-1",
    cost: 110.0,
  },
  {
    id: "maint-2",
    vehicleId: "veh-1",
    km: 20000,
    description: "Troca de pneu dianteiro Michelin e pastilhas",
    date: "2026-02-14T09:30:00Z",
    tenantId: "tenant-1",
    cost: 320.0,
  },
  {
    id: "maint-3",
    vehicleId: "veh-2",
    km: 10000,
    description: "Revisão de 10.000 km, troca de óleo Motul 5100 e filtro Fram",
    date: "2026-04-05T11:15:00Z",
    tenantId: "tenant-1",
    cost: 210.0,
  },
  {
    id: "maint-4",
    vehicleId: "veh-3",
    km: 35000,
    description: "Troca de correia de transmissão e roletes",
    date: "2026-05-20T16:20:00Z",
    tenantId: "tenant-1",
    cost: 180.0,
  },
];
