// Catálogo de Veículos extraído de veiculos/marcas-motos.csv, modelos-moto.csv, marcas-nautica.csv e modelos-nautica.csv

export type VehicleCategory = 'MOTO' | 'NAUTICA' | 'TODOS';

export const MOTO_BRANDS: string[] = [
  "ACELLERA",
  "ADLY",
  "AGRALE",
  "AMAZONAS",
  "APRILIA",
  "ARIEL",
  "ATALA",
  "BAJAJ",
  "BENELLI",
  "BETA",
  "BIMOTA",
  "BIRELLI",
  "BMW",
  "BRANDY",
  "BRAVA",
  "BRAVAX",
  "BRP",
  "BUELL",
  "BUENO",
  "BULL",
  "CAGIVA",
  "CAN-AM",
  "DAELIM",
  "DAFRA",
  "DAYANG",
  "DAYUN",
  "DERBI",
  "DITALLY",
  "DUCAR",
  "DUCATI",
  "EMME",
  "FBM",
  "FYM",
  "GARELLI",
  "GARINNI",
  "GARRA",
  "GAS GAS",
  "GREEN",
  "HAOBAO",
  "HARLEY-DAVIDSON",
  "HARTFORD",
  "HERO",
  "HONDA",
  "HUSABERG",
  "HUSQVARNA",
  "INDIAN",
  "IROS",
  "JAWA",
  "JIAPENG VOLCANO",
  "JOHNNYPAG",
  "JONNY",
  "KAHENA",
  "KASINSKI",
  "KAWASAKI",
  "KIMCO",
  "KTM",
  "LAMBRETA",
  "LANDUM",
  "LAQUILA",
  "LAVRALE",
  "LEOPARD",
  "LERIVO",
  "LIFAN",
  "LON-V",
  "MAHINDRA",
  "MALAGUTI",
  "MARVA",
  "MIZA",
  "MOBILETE",
  "MOTO GUZZI",
  "MRX",
  "MV AUGUSTA",
  "MVK",
  "ORCA",
  "OUTROS",
  "PEGASSI",
  "PIAGGIO",
  "POLARIS",
  "REGAL RAPTOR",
  "SANYANG",
  "SCOOTER",
  "SHINERAY",
  "SIAMOTO",
  "SUNDOWN",
  "SUZUKI",
  "TARGOS",
  "TRAXX",
  "TRICICLO",
  "TRICKER",
  "VENTO",
  "VICTORY",
  "WALK MACHINE",
  "WOLVER",
  "WUYANG",
  "X MOTOS",
  "YAMAHA",
  "ZONGSHEN"
];

export const NAUTICA_BRANDS: string[] = [
  "ACELLERA",
  "AGUZ",
  "ALBATROZ",
  "ALTERNATIVA",
  "ALUMACRAFT",
  "AQUA",
  "AQUATERRA",
  "ARBOAT",
  "ARMADA",
  "ARTHMARINE",
  "AVALON",
  "AXTOR MARINE",
  "AZIMUT",
  "B3",
  "BAIA",
  "BAJA MARINE",
  "BATE VENTO",
  "BAYLINER",
  "BELASSI",
  "BENETEAU",
  "BENETTI",
  "BERTRAM",
  "BILGIN",
  "BMYD",
  "BRAMADOR",
  "BRASBOATS",
  "BRAVA YACHTS",
  "BRAZILIAN BOAT",
  "BRUDDEN",
  "CANTIERI DI PISA",
  "CAPRICE",
  "CARABELLI",
  "CARBRASMAR",
  "CENTURY",
  "CHRIS CRAFT",
  "CIMITARRA",
  "COBRA",
  "COLUNNA",
  "CORAL",
  "CRANCHI",
  "CROWNLINE",
  "DELTA",
  "DIAMAR",
  "DOLPHIN",
  "DONZI",
  "DREAMBOATS",
  "ECOMARINER",
  "EDGEWATER",
  "ESQUIMAR",
  "EUROBOATS",
  "EVINRUDE",
  "EVOLUTION",
  "EVOLVE",
  "FAIRLINE",
  "FERRETTI",
  "FIBRAFORT",
  "FISHING",
  "FLASH",
  "FLEXBOAT",
  "FLIPPER",
  "FLORIDA",
  "FLYBOAT",
  "FORCE ONE",
  "FORMULA",
  "FOUNTAINE PAJOT",
  "FOUR WINNS",
  "FS YACHTS",
  "FUTURA",
  "GALEON",
  "GAMPER",
  "GENESIS",
  "GIANETTI",
  "HARRIS FLOTEBOTE",
  "HD MARINE",
  "HEESEN",
  "HOLOS",
  "HONDA",
  "IMPERIO",
  "INACE",
  "INTECH",
  "INTERMARINE",
  "JEANNEAU",
  "KALMAR",
  "KAWASAKI",
  "KRAUSE",
  "LAGOON",
  "LANCER",
  "LAZZARA",
  "LENZI",
  "LEVEFORT",
  "LOTHAR",
  "LOWE",
  "LUNA",
  "LUND",
  "MAESTRALE",
  "MAGIS",
  "MAGNA",
  "MAGNUM",
  "MALIBU",
  "MARES",
  "MARINER",
  "MASTERBOAT",
  "MASTERCRAFT",
  "MAXIMA",
  "MCP YACHTS",
  "MERCEDES-BENZ",
  "MERCURY MARINE",
  "METALGLASS",
  "MIDNIGHT EXPRESS",
  "MILLENIUM",
  "MINASFORTE",
  "MJ YACHTS",
  "MOCHI CRAFT",
  "MONTE CARLO",
  "MONTEREY",
  "MOOMBA",
  "MOONEN",
  "MTI",
  "MWM",
  "NAUTIFLEX",
  "NAUTIQUE",
  "OUTROS",
  "PALMER JOHNSON",
  "PAPA E PALAZZINI",
  "PERI YACHTS",
  "PERSHING",
  "PHANTOM",
  "PHOENIX",
  "POLARIS BOATS",
  "PRESTIGE",
  "PRINCESS",
  "PROMAR",
  "PSARI",
  "RANGER",
  "REAL POWER BOATS",
  "RECON",
  "REGAL",
  "RIOSTAR",
  "RIVA",
  "RIVAL",
  "ROYAL MARINER",
  "RUNNER",
  "SAGA",
  "SAIL MASTER",
  "SAPPHIRE",
  "SCHAEFER",
  "SEA CREST",
  "SEA HAWK",
  "SEA RAY",
  "SEA-DOO",
  "SEGUE YACHTS",
  "SESSA MARINE",
  "SILVERTON",
  "SKIPPER",
  "STATEMENT",
  "STERLING",
  "STRIDER",
  "SUNFLASH",
  "SUNLINE",
  "SUNREEF",
  "SUNSEEKER",
  "SUPERBOATS",
  "SUPRA",
  "SUZUKI",
  "TECHNOMARINE",
  "TECNOBOATS",
  "TEMPEST",
  "TOHATSU",
  "TOP BOATS",
  "TRITON",
  "TRIUMPH BOATS",
  "VEGA",
  "VENTURA",
  "VICTORY YACHTS",
  "VOLVO",
  "WALGLASS",
  "WELLCRAFT",
  "YACXO",
  "YAMAHA",
  "YANMAR",
  "ZEFIR",
  "ZODIAC",
  "ZONDA"
];

export const ALL_BRANDS: string[] = [
  "ACELLERA",
  "ADLY",
  "AGRALE",
  "AGUZ",
  "ALBATROZ",
  "ALTERNATIVA",
  "ALUMACRAFT",
  "AMAZONAS",
  "APRILIA",
  "AQUA",
  "AQUATERRA",
  "ARBOAT",
  "ARIEL",
  "ARMADA",
  "ARTHMARINE",
  "ATALA",
  "AVALON",
  "AXTOR MARINE",
  "AZIMUT",
  "B3",
  "BAIA",
  "BAJA MARINE",
  "BAJAJ",
  "BATE VENTO",
  "BAYLINER",
  "BELASSI",
  "BENELLI",
  "BENETEAU",
  "BENETTI",
  "BERTRAM",
  "BETA",
  "BILGIN",
  "BIMOTA",
  "BIRELLI",
  "BMW",
  "BMYD",
  "BRAMADOR",
  "BRANDY",
  "BRASBOATS",
  "BRAVA",
  "BRAVA YACHTS",
  "BRAVAX",
  "BRAZILIAN BOAT",
  "BRP",
  "BRUDDEN",
  "BUELL",
  "BUENO",
  "BULL",
  "CAGIVA",
  "CAN-AM",
  "CANTIERI DI PISA",
  "CAPRICE",
  "CARABELLI",
  "CARBRASMAR",
  "CENTURY",
  "CHRIS CRAFT",
  "CIMITARRA",
  "COBRA",
  "COLUNNA",
  "CORAL",
  "CRANCHI",
  "CROWNLINE",
  "DAELIM",
  "DAFRA",
  "DAYANG",
  "DAYUN",
  "DELTA",
  "DERBI",
  "DIAMAR",
  "DITALLY",
  "DOLPHIN",
  "DONZI",
  "DREAMBOATS",
  "DUCAR",
  "DUCATI",
  "ECOMARINER",
  "EDGEWATER",
  "EMME",
  "ESQUIMAR",
  "EUROBOATS",
  "EVINRUDE",
  "EVOLUTION",
  "EVOLVE",
  "FAIRLINE",
  "FBM",
  "FERRETTI",
  "FIBRAFORT",
  "FISHING",
  "FLASH",
  "FLEXBOAT",
  "FLIPPER",
  "FLORIDA",
  "FLYBOAT",
  "FORCE ONE",
  "FORMULA",
  "FOUNTAINE PAJOT",
  "FOUR WINNS",
  "FS YACHTS",
  "FUTURA",
  "FYM",
  "GALEON",
  "GAMPER",
  "GARELLI",
  "GARINNI",
  "GARRA",
  "GAS GAS",
  "GENESIS",
  "GIANETTI",
  "GREEN",
  "HAOBAO",
  "HARLEY-DAVIDSON",
  "HARRIS FLOTEBOTE",
  "HARTFORD",
  "HD MARINE",
  "HEESEN",
  "HERO",
  "HOLOS",
  "HONDA",
  "HUSABERG",
  "HUSQVARNA",
  "IMPERIO",
  "INACE",
  "INDIAN",
  "INTECH",
  "INTERMARINE",
  "IROS",
  "JAWA",
  "JEANNEAU",
  "JIAPENG VOLCANO",
  "JOHNNYPAG",
  "JONNY",
  "KAHENA",
  "KALMAR",
  "KASINSKI",
  "KAWASAKI",
  "KIMCO",
  "KRAUSE",
  "KTM",
  "LAGOON",
  "LAMBRETA",
  "LANCER",
  "LANDUM",
  "LAQUILA",
  "LAVRALE",
  "LAZZARA",
  "LENZI",
  "LEOPARD",
  "LERIVO",
  "LEVEFORT",
  "LIFAN",
  "LON-V",
  "LOTHAR",
  "LOWE",
  "LUNA",
  "LUND",
  "MAESTRALE",
  "MAGIS",
  "MAGNA",
  "MAGNUM",
  "MAHINDRA",
  "MALAGUTI",
  "MALIBU",
  "MARES",
  "MARINER",
  "MARVA",
  "MASTERBOAT",
  "MASTERCRAFT",
  "MAXIMA",
  "MCP YACHTS",
  "MERCEDES-BENZ",
  "MERCURY MARINE",
  "METALGLASS",
  "MIDNIGHT EXPRESS",
  "MILLENIUM",
  "MINASFORTE",
  "MIZA",
  "MJ YACHTS",
  "MOBILETE",
  "MOCHI CRAFT",
  "MONTE CARLO",
  "MONTEREY",
  "MOOMBA",
  "MOONEN",
  "MOTO GUZZI",
  "MRX",
  "MTI",
  "MV AUGUSTA",
  "MVK",
  "MWM",
  "NAUTIFLEX",
  "NAUTIQUE",
  "ORCA",
  "OUTROS",
  "PALMER JOHNSON",
  "PAPA E PALAZZINI",
  "PEGASSI",
  "PERI YACHTS",
  "PERSHING",
  "PHANTOM",
  "PHOENIX",
  "PIAGGIO",
  "POLARIS",
  "POLARIS BOATS",
  "PRESTIGE",
  "PRINCESS",
  "PROMAR",
  "PSARI",
  "RANGER",
  "REAL POWER BOATS",
  "RECON",
  "REGAL",
  "REGAL RAPTOR",
  "RIOSTAR",
  "RIVA",
  "RIVAL",
  "ROYAL MARINER",
  "RUNNER",
  "SAGA",
  "SAIL MASTER",
  "SANYANG",
  "SAPPHIRE",
  "SCHAEFER",
  "SCOOTER",
  "SEA CREST",
  "SEA HAWK",
  "SEA RAY",
  "SEA-DOO",
  "SEGUE YACHTS",
  "SESSA MARINE",
  "SHINERAY",
  "SIAMOTO",
  "SILVERTON",
  "SKIPPER",
  "STATEMENT",
  "STERLING",
  "STRIDER",
  "SUNDOWN",
  "SUNFLASH",
  "SUNLINE",
  "SUNREEF",
  "SUNSEEKER",
  "SUPERBOATS",
  "SUPRA",
  "SUZUKI",
  "TARGOS",
  "TECHNOMARINE",
  "TECNOBOATS",
  "TEMPEST",
  "TOHATSU",
  "TOP BOATS",
  "TRAXX",
  "TRICICLO",
  "TRICKER",
  "TRITON",
  "TRIUMPH BOATS",
  "VEGA",
  "VENTO",
  "VENTURA",
  "VICTORY",
  "VICTORY YACHTS",
  "VOLVO",
  "WALGLASS",
  "WALK MACHINE",
  "WELLCRAFT",
  "WOLVER",
  "WUYANG",
  "X MOTOS",
  "YACXO",
  "YAMAHA",
  "YANMAR",
  "ZEFIR",
  "ZODIAC",
  "ZONDA",
  "ZONGSHEN"
];

export const BRAND_MODELS_MAP: Record<string, string[]> = {
  "HONDA": [
    "AERO CBX 150",
    "AFRICA TWIN XRV 750",
    "AMERICA",
    "BIZ",
    "BOLDOR CB 900",
    "CB 1000R",
    "CB 125",
    "CB 1300",
    "CB 300R",
    "CB 400",
    "CB 50",
    "CB 500",
    "CB 600 HORNET",
    "CBF 600",
    "CBR 1000F",
    "CBR 250",
    "CBR 400RR",
    "CBR 450",
    "CBR 600",
    "CBX 1000",
    "CBX 750F",
    "CD 125",
    "CG 125",
    "CG CARGO/JOB",
    "CG FAN",
    "CG TITAN",
    "CG TODAY",
    "CH 125R",
    "CR 125",
    "CR 250",
    "CR 85",
    "CRF 110/150",
    "CRF 230/250",
    "CRF 450",
    "DREAM",
    "DUTY",
    "FIREBLADE CBR",
    "FURY",
    "GL GOLD WING",
    "HERO",
    "LEAD",
    "MAGNA VF 750C",
    "ML 125",
    "MOTOR DE BARCO",
    "NC 700X",
    "NSR 500",
    "NX 200/250",
    "NX 350 SAHARA",
    "NX 400 FALCON",
    "NX 650 DOMINATOR",
    "NXR BROS",
    "PACIFIC COAST",
    "PAN-EUROPEAN ST",
    "PC 50",
    "PCX",
    "POP 100",
    "RC",
    "SHADOW",
    "STRADA CBX 200",
    "STUNNER",
    "SUPER HAWK",
    "SUPERBLACKBIRD CBR 1100XX",
    "TORNADO XR 250",
    "TRX",
    "TURUNA 125",
    "TWISTER CBX 250",
    "VALKYRIE",
    "VARADERO XL 1000V",
    "VFR 1200",
    "VLR 350",
    "VTR",
    "VTX",
    "XL",
    "XL 700V TRANSALP",
    "XLR",
    "XLX",
    "XR",
    "XRE 300"
  ],
  "YAMAHA": [
    "AEROX",
    "ALBA",
    "AXIS",
    "BWS",
    "CRYPTON T115",
    "DRAG STAR",
    "DT 200",
    "DT 50",
    "EC-02",
    "ECCY",
    "FACTOR YBR125",
    "FAZER FZ1",
    "FAZER FZ6",
    "FAZER YS150",
    "FAZER YS250",
    "FJR1300",
    "FROG",
    "FS1",
    "FX CRUISER HO",
    "FX CRUISER SHO",
    "FX CRUISER SVHO",
    "FX SHO",
    "FX SVHO",
    "FZ-09",
    "FZR1000",
    "FZR250",
    "FZR400",
    "FZR600",
    "FZS",
    "GLADIATOR",
    "GRIZZLY",
    "JOG",
    "LAGEND",
    "LANDER XTZ 250",
    "LIBERO",
    "MAJESTY",
    "MEST",
    "MIDNIGHT STAR XVS",
    "MORPHOUS",
    "MOTOR DE BARCO",
    "MT-01",
    "MT-03",
    "MT-07",
    "NEO AT",
    "PAS",
    "PASSOL",
    "QT50",
    "RD 135",
    "RD 350 VIUVA NEGRA",
    "RD 50",
    "ROYAL STAR",
    "RX",
    "SJ 700",
    "SR500",
    "SRX 400",
    "SRX 600",
    "SUPERJET",
    "TDM",
    "TDR 180",
    "TMAX",
    "TRX",
    "TT 125",
    "TT-R",
    "TX500",
    "TZ 250",
    "TZR",
    "V-MAX 1200",
    "V-MAX 1680",
    "V-STAR",
    "VIRAGO 1400",
    "VIRAGO 250",
    "VIRAGO 400",
    "VIRAGO 535",
    "VIRAGO 750",
    "VX 700",
    "VX CRUISER",
    "VX DELUXE",
    "VX SPORT",
    "VXR",
    "VXS",
    "WAVE BLASTER",
    "WAVE RAIDER",
    "WR 250F",
    "WR 450F",
    "XF50X",
    "XJ6",
    "XJR",
    "XR 180",
    "XS1100",
    "XS400",
    "XS500",
    "XS650",
    "XS750",
    "XS850",
    "XT 1200Z SUPER TENERE",
    "XT 225",
    "XT 600",
    "XT 660R",
    "XT 660Z TENERE",
    "XTZ 125",
    "XTZ 250 TENERE",
    "XTZ 750 SUPER TENERE",
    "XZ 550",
    "YFM 700R",
    "YFS",
    "YZ 125",
    "YZ 250",
    "YZ 450",
    "YZ 85LW",
    "YZF 600R",
    "YZF R1",
    "YZF R6",
    "YZR 500"
  ],
  "KASINSKI": [
    "COMET GT 250",
    "COMET GT 650",
    "COMET GT-R 250",
    "COMET GT-R 650",
    "CRUISE",
    "CRZ",
    "ERO",
    "FLASH",
    "FURIA",
    "GF",
    "MAGIK",
    "MIDAS",
    "MIRAGE",
    "MOTOKAR",
    "PRIMA",
    "RX",
    "SETA",
    "SOFT",
    "SUPER CAB",
    "TN",
    "WAY",
    "WIN"
  ],
  "SUZUKI": [
    "ADDRESS",
    "AE 50",
    "B-KING GSX 1300",
    "BANDIT 1200",
    "BANDIT 250",
    "BANDIT 400",
    "BANDIT 600",
    "BANDIT GSF 750",
    "BOULEVARD",
    "BURGMAN AN",
    "DR",
    "FREEWIND 650",
    "GS 500",
    "GSI",
    "GSR",
    "GSX",
    "GSX-R GIXXER/SRAD",
    "GT",
    "HAYABUSA",
    "INTRUDER",
    "INTRUDER CUSTOM",
    "JOB",
    "KATANA",
    "LETS II",
    "LT",
    "MARAUDER GZ",
    "MARAUDER VZ",
    "MOTOR DE BARCO",
    "RF",
    "RM 250",
    "RV",
    "SAVAGE",
    "SV",
    "TL",
    "V-STROM DL",
    "VX 800",
    "YES EN 125"
  ],
  "AGRALE": [
    "CITY",
    "DAKAR",
    "ELEFANT",
    "ELEFANTRE",
    "EXPLORER",
    "FORCE",
    "JUNIOR",
    "SST",
    "SUPER CITY",
    "SXT",
    "TCHAU"
  ],
  "SUNDOWN": [
    "AKROS",
    "ERGON",
    "FIFTY",
    "FUTURE",
    "HUNTER",
    "MAX",
    "PALIO",
    "PGO",
    "STX",
    "STX MOTARD",
    "SUPER FIFTY",
    "VBLADE",
    "WEB",
    "WEB EVO"
  ],
  "GARINNI": [
    "GR 125S/ST",
    "GR 125Z",
    "GR 150P/PI",
    "GR 500",
    "GR08T4",
    "GR125T3",
    "GR125U",
    "GR150ST",
    "GR150T3",
    "GR150TI",
    "GR150U",
    "GR250T3",
    "GRI 50"
  ],
  "AMAZONAS": [
    "AME-110",
    "AME-150",
    "AME-250",
    "AME-LX"
  ],
  "APRILIA": [
    "AREA-51",
    "CLASSIC",
    "LEONARDO",
    "MOTO",
    "PEGASO",
    "RALLY",
    "RS",
    "RSV MILLE",
    "RX",
    "SCARABEO",
    "SONIC",
    "SR",
    "SR RACING",
    "SR WWW"
  ],
  "ATALA": [
    "CALIFFONE",
    "MASTER",
    "SKEGIA"
  ],
  "BAJAJ": [
    "CHAMPION",
    "CLASSIC"
  ],
  "BENELLI": [
    "TNT",
    "TRE"
  ],
  "BETA": [
    "MX-50"
  ],
  "BIMOTA": [
    "DB4",
    "DB5R",
    "DB6",
    "DB6R",
    "DB7",
    "MANTRA",
    "SBR8",
    "TESI"
  ],
  "BMW": [
    "AIRHEAD",
    "C1",
    "F650CS",
    "F650GS",
    "F800GS",
    "G650GS",
    "K100",
    "K1200GS",
    "K1200GT",
    "K1200R",
    "K1200S",
    "K1300GT",
    "K1300R",
    "K75",
    "R1150GS",
    "R1200C",
    "R1200RT",
    "R27",
    "R32",
    "R51/3",
    "R60",
    "R75",
    "R75/5",
    "R90S",
    "S1000RR"
  ],
  "BRANDY": [
    "ELEGANT",
    "FOSTI",
    "PISTA",
    "TURBO",
    "ZANELLA"
  ],
  "BRAVA": [
    "ALPINA",
    "ALTINO",
    "APOLO",
    "AQUILA",
    "DAYSTAR ROUTIER",
    "ELEKTRA",
    "NEVADA",
    "TEXANA",
    "WINSTAR",
    "YB"
  ],
  "BRP": [
    "CAN-AM"
  ],
  "BUELL": [
    "1125",
    "FIREBOLT",
    "LIGHTNING",
    "ULYSSES"
  ],
  "BUENO": [
    "JBR"
  ],
  "CAGIVA": [
    "CANYON",
    "ELEFANT",
    "GRAN CANYON",
    "MITO",
    "NAVIGATOR",
    "PLANET",
    "ROADSTER",
    "V-RAPTOR",
    "W-16"
  ],
  "MOBILETE": [
    "MOBILETE"
  ],
  "DAELIM": [
    "ALTINO",
    "MESSAGE",
    "VC",
    "VF",
    "VS",
    "VT",
    "VX"
  ],
  "DAFRA": [
    "APACHE",
    "CITYCOM",
    "KANSAS",
    "LASER",
    "NEXT",
    "RIVA",
    "ROADWIN",
    "SMART",
    "SPEED",
    "SUPER",
    "ZIG"
  ],
  "DAYANG": [
    "DY100-31",
    "DY110-20",
    "DY125-18",
    "DY125-36A",
    "DY125-37",
    "DY125-5",
    "DY125-52",
    "DY150-12",
    "DY200",
    "DY50"
  ],
  "DAYUN": [
    "CARGO 150",
    "CARGO 200",
    "CITY",
    "DY125-8",
    "DY150GY",
    "DY250-2",
    "PHANTON",
    "SPACE",
    "SUMMER"
  ],
  "DERBI": [
    "ATLANTIS",
    "GPR",
    "PREDATOR",
    "RED BULLET",
    "REPLICAS",
    "SENDA"
  ],
  "DUCATI": [
    "1098",
    "1198",
    "749",
    "848",
    "996",
    "998",
    "999",
    "999R",
    "DESMOSEDICI",
    "DIAVEL",
    "HYPERMOTARD",
    "MONSTER",
    "MULTISTRADA",
    "SPORTCLASSIC",
    "SS",
    "ST-2",
    "ST-4",
    "STREETFIGHTER"
  ],
  "EMME": [
    "MIRAGE",
    "ONE",
    "ONE RACING"
  ],
  "FYM": [
    "FY100-10A",
    "FY125-19",
    "FY125-20",
    "FY125EY-2",
    "FY125Y-3",
    "FY150-3",
    "FY150T-18",
    "FY250"
  ],
  "GAS GAS": [
    "BOY",
    "ENDUCROSS",
    "MC",
    "PAMPERA",
    "ROOKIE ENDURO",
    "TX BOY",
    "TXT",
    "TXT ROOKIE"
  ],
  "GREEN": [
    "EASY",
    "RUNNER",
    "SAFARI",
    "SPORT"
  ],
  "HAOBAO": [
    "HB-110",
    "HB-125",
    "HB-150",
    "HB-50"
  ],
  "HARLEY-DAVIDSON": [
    "CVO",
    "DYNA",
    "SOFTAIL",
    "SPORTSTER",
    "TOURING ELECTRA GLIDE",
    "TOURING ROAD KING",
    "TOURING STREET GLIDE",
    "V-ROD"
  ],
  "HARTFORD": [
    "LEGION"
  ],
  "HERO": [
    "ANKUR",
    "PUCH",
    "STREAM"
  ],
  "HUSABERG": [
    "FE"
  ],
  "HUSQVARNA": [
    "CR",
    "HUSQY",
    "SM",
    "SMR",
    "TC",
    "TE",
    "WR",
    "WRE"
  ],
  "IROS": [
    "ACTION",
    "BRAVE",
    "IZY 50",
    "MATRIX",
    "MOVING",
    "ONE",
    "VINTAGE",
    "WARRIOR"
  ],
  "JIAPENG VOLCANO": [
    "JP"
  ],
  "JOHNNYPAG": [
    "BARHOG",
    "PROSTREET",
    "SPYDER"
  ],
  "JONNY": [
    "ATLANTIC",
    "HYPE",
    "JONNY",
    "NAKED",
    "ORBIT",
    "PEGASUS",
    "QUICK",
    "RACER",
    "TEXAS",
    "TR"
  ],
  "KAHENA": [
    "AMAZONAS",
    "DUAL",
    "TOP"
  ],
  "KAWASAKI": [
    "AVAJET",
    "BAIO",
    "CONCOURS",
    "D-TRACKER",
    "ELIMINATOR",
    "ER-5",
    "ER-6N",
    "GTR",
    "KDX",
    "KLE",
    "KLR",
    "KLX 110/140",
    "KLX 250/300",
    "KLX 400/450",
    "KX 100/125",
    "KX 250",
    "KX 450/500",
    "KX 65/85",
    "KZ",
    "MAXI",
    "NINJA 1000",
    "NINJA 1100",
    "NINJA 1200",
    "NINJA 1400",
    "NINJA 250",
    "NINJA 300",
    "NINJA 600",
    "NINJA 700",
    "NINJA 900",
    "SUPER SHERPA",
    "ULTRA 300LX",
    "ULTRA 300X",
    "ULTRA LX",
    "VERSYS",
    "VERSYS 1000",
    "VERSYS CITY",
    "VERSYS GRAND TOURER",
    "VERSYS TOURER",
    "VOYAGER",
    "VULCAN",
    "Z1000",
    "Z750",
    "Z800",
    "ZR",
    "ZRX",
    "ZXI 1100",
    "ZXI 750",
    "ZXI 900",
    "ZZR"
  ],
  "KIMCO": [
    "DJW",
    "MBOY",
    "PEOPLE",
    "ZING"
  ],
  "LAQUILA": [
    "AKROS",
    "ERGON",
    "NIX"
  ],
  "LANDUM": [
    "MOTO TRUCK"
  ],
  "LAVRALE": [
    "QUATTOR"
  ],
  "LERIVO": [
    "FORMIGAO"
  ],
  "LIFAN": [
    "CARGO",
    "CC125",
    "CC150",
    "COOL STAR 125",
    "CROSS",
    "GLOW 110S",
    "HIKER",
    "IV",
    "JOJO 110",
    "KP150",
    "KP150F",
    "LF100",
    "LF125",
    "PK110F",
    "PK125",
    "POWER KING",
    "POWER MAN 250",
    "STEED 250",
    "TB125",
    "TRAVELLER",
    "X3"
  ],
  "LON-V": [
    "DE LUXE",
    "E RETRO",
    "LY"
  ],
  "TRICICLO": [
    "TRICICLO"
  ],
  "MALAGUTI": [
    "CIAK",
    "SPIDER"
  ],
  "MIZA": [
    "DRAGO",
    "EASY",
    "FAST",
    "SKEMA",
    "VITE"
  ],
  "MOTO GUZZI": [
    "CALIFORNIA",
    "LE MANS",
    "QUOTA",
    "V11"
  ],
  "MRX": [
    "230R"
  ],
  "MV AUGUSTA": [
    "BRUTALE",
    "F4"
  ],
  "MVK": [
    "BIG FORCE",
    "BLACK STAR",
    "BRX",
    "DUAL",
    "FENIX",
    "FENIX GOLD",
    "FOX",
    "GO",
    "HALLEY",
    "JURASIC",
    "MA",
    "SIMBA",
    "SPORT",
    "SPYDER",
    "STREET",
    "SUPER",
    "XRT"
  ],
  "ORCA": [
    "AX",
    "JC",
    "QM"
  ],
  "PEGASSI": [
    "BR III"
  ],
  "OUTROS": [
    "ADVENTURER",
    "BONNEVILLE",
    "BUXY",
    "DAYTONA",
    "ELYSEO",
    "KART",
    "LEGEND",
    "ROCKET",
    "SCOOTELEC",
    "SCRAMBLER",
    "SPEED TRIPLE",
    "SPEEDAKE",
    "SPEEDFIGHT",
    "SPRINT",
    "SQUAB",
    "STREET TRIPLE",
    "THRUXTON",
    "THUNDERBIRD",
    "TIGER",
    "TREKKER",
    "TRIDENT",
    "TROPHY",
    "TT-600",
    "VIVACITY",
    "ZENITH"
  ],
  "PIAGGIO": [
    "BEVERLY",
    "LIBERTY",
    "MP3",
    "NRG",
    "RUNNER",
    "VESPA",
    "ZIP"
  ],
  "REGAL RAPTOR": [
    "BLACK JACK",
    "FENIX GOLD",
    "GHOST",
    "SPYDER"
  ],
  "SANYANG": [
    "ENJOY",
    "HUSKY",
    "PASSING"
  ],
  "SHINERAY": [
    "BIKE 50",
    "BRAVO 200",
    "CARGO 200",
    "CUSTOM 250",
    "DISCOVER 250",
    "EAGLE 50",
    "EXPLORER 150",
    "F35/F40",
    "FUTURE 150",
    "INDIANAPOLIS 200",
    "JET 125",
    "JET 50",
    "LIBERTY 50",
    "MAX 150",
    "NEW 200",
    "NEW 50",
    "NEW WAVE 125",
    "PHOENIX 50",
    "RACING 200",
    "RETRO 50",
    "STRONG 250",
    "SUPER SMART 50",
    "VENICE 50",
    "X2 250",
    "XY 250"
  ],
  "SIAMOTO": [
    "SCROSS"
  ],
  "TARGOS": [
    "TRIMOTO"
  ],
  "TRAXX": [
    "BEST",
    "CJ",
    "DUNNA 600",
    "FLY 135",
    "JH",
    "JL",
    "JOTO 135",
    "MOBY 50",
    "MONTEZ 250",
    "SHARK",
    "SKY 125",
    "STAR 50",
    "VICO",
    "WORK 125"
  ],
  "VENTO": [
    "REBELLIAN",
    "TRITON",
    "VTHUNDER"
  ],
  "WUYANG": [
    "WY"
  ],
  "X MOTOS": [
    "XM"
  ],
  "LAMBRETA": [
    "LAMBRETA"
  ],
  "SCOOTER": [
    "SCOOTER"
  ],
  "ADLY": [
    "ATV",
    "JAGUAR",
    "RT"
  ],
  "ZONGSHEN": [
    "125 ZS",
    "ZS 200"
  ],
  "BIRELLI": [
    "BW 125"
  ],
  "WALK MACHINE": [
    "WALK MACHINE"
  ],
  "FBM": [
    "KAPRA",
    "MZ 250",
    "PASSEIO",
    "RALLYE"
  ],
  "ARIEL": [
    "GOLDEN ARROW",
    "M2F",
    "RED HUNTER",
    "W/NG"
  ],
  "MAHINDRA": [
    "DURO",
    "RODEO"
  ],
  "DUCAR": [
    "150"
  ],
  "DITALLY": [
    "BRUTTUS",
    "JOY PLUS",
    "OUTCROSS",
    "PASSION",
    "PIT BULL",
    "TREND",
    "WAKE 500"
  ],
  "MARVA": [
    "FOX 150R",
    "HERCULES 200",
    "HS 150 FIRE",
    "LF250ST",
    "LF400ST",
    "ONIX 50R",
    "UFO 50",
    "VR 150 WIND"
  ],
  "WOLVER": [
    "KN 125 S",
    "KN 150",
    "KN 50 S"
  ],
  "BULL": [
    "HB"
  ],
  "CAN-AM": [
    "DS 250",
    "DS 450",
    "DS 90",
    "OUTLANDER 400",
    "OUTLANDER 500",
    "OUTLANDER 650",
    "OUTLANDER 800R",
    "OUTLANDER MAX 400",
    "OUTLANDER MAX 500",
    "OUTLANDER MAX 650",
    "OUTLANDER MAX 800R",
    "OUTLANDER MAX LTD 800R",
    "RENEGADE 500",
    "RENEGADE 800R",
    "RS",
    "RT"
  ],
  "KTM": [
    "1190 ADVENTURE",
    "1190 RC8 R",
    "125 SX",
    "150 SX",
    "150 XC",
    "200 XC",
    "250 SX",
    "250 XC",
    "300 XC",
    "350 EXC",
    "350 SX",
    "450 SX",
    "450 SX-F",
    "450 XC",
    "450 XC-F/W",
    "50 SX",
    "500 EXC",
    "505 SX",
    "525 XC",
    "65 SX",
    "690 DUKE",
    "690 ENDURO R",
    "85 SX",
    "990 ADVENTURE BAJA",
    "990 SM T"
  ],
  "ACELLERA": [
    "ACX 250F",
    "FRONTLANDER 500",
    "FRONTLANDER 800 EFI",
    "HOTZOO SPORT 90",
    "MOTOR DE BARCO",
    "QUADRILANDER 300",
    "QUADRILANDER 400",
    "QUADRILANDER 600",
    "SPORTLANDER 150R",
    "SPORTLANDER 250XR",
    "SPORTLANDER 350ZX",
    "SPORTLANDER 450TR"
  ],
  "POLARIS": [
    "BRUTUS",
    "OUTLAW 50",
    "OUTLAW 90",
    "PHOENIX 200",
    "RANGER 400",
    "RANGER 570",
    "RANGER 6X6",
    "RANGER 800",
    "RANGER 800 MIDSIZE",
    "RANGER CREW 570",
    "RANGER CREW 800",
    "RANGER CREW 900",
    "RANGER CREW DIESEL",
    "RANGER DIESEL",
    "RANGER EV",
    "RANGER XP 900",
    "RZR 170",
    "RZR 4 1000",
    "RZR 4 800",
    "RZR 4 900",
    "RZR 570",
    "RZR 800",
    "RZR 800 XC",
    "RZR 900",
    "RZR S 800",
    "RZR XP 1000",
    "SCRAMBLER XP 1000 EPS",
    "SCRAMBLER XP 850 HO",
    "SPORTSMAN 400 HO",
    "SPORTSMAN 550 EPS",
    "SPORTSMAN 570",
    "SPORTSMAN 800 EFI",
    "SPORTSMAN 90",
    "SPORTSMAN BIG BOSS 6X6 800",
    "SPORTSMAN TOURING 550",
    "SPORTSMAN TOURING 570",
    "SPORTSMAN TOURING 850",
    "SPORTSMAN WV850 HO",
    "SPORTSMAN X2 550",
    "SPORTSMAN XP 850"
  ],
  "VICTORY": [
    "BOARDWALK",
    "CORY NESS CROSS COUNTRY TOUR",
    "CROSS COUNTRY",
    "CROSS COUNTRY 8-BALL",
    "CROSS COUNTRY TOUR",
    "CROSS COUNTRY TOUR ANNIVERSARY",
    "CROSS ROADS 8-BALL",
    "CROSS ROADS CLASSIC",
    "HAMMER 8-BALL",
    "HARD-BALL",
    "HIGH-BALL",
    "JACKPOT",
    "JUDGE",
    "NESS CROSS COUNTRY",
    "NESS VISION",
    "VEGAS 8-BALL",
    "VISION TOUR",
    "ZACH NESS CROSS COUNTRY"
  ],
  "INDIAN": [
    "CHIEF CLASSIC",
    "CHIEF VINTAGE",
    "CHIEFTAIN"
  ],
  "BRAVAX": [
    "AX 200",
    "BR 250 D1",
    "BVX 125",
    "BVX 130 STREET",
    "BVX 150 S1",
    "BVX 200",
    "BX 260",
    "CARGO 260",
    "F2 PLUS",
    "SUPER F1",
    "SUPER F2",
    "SUPER F3",
    "TR 150 D6"
  ],
  "ECOMARINER": [
    "20",
    "25",
    "36",
    "39",
    "45",
    "55",
    "ALFA 300",
    "STAR 140"
  ],
  "VENTURA": [
    "V160 COMFORT",
    "V175 COMFORT",
    "V180 COMFORT",
    "V195 COMFORT",
    "V210 COMFORT",
    "V215 COMFORT",
    "V230 GII COMFORT",
    "V250 COMFORT",
    "V265 COMFORT",
    "V330 PREMIUM",
    "V350 PREMIUM",
    "V410 PREMIUM"
  ],
  "FIBRAFORT": [
    "FOCKER 160",
    "FOCKER 19",
    "FOCKER 205",
    "FOCKER 215",
    "FOCKER 230",
    "FOCKER 240",
    "FOCKER 255",
    "FOCKER 265",
    "FOCKER 265 OPEN",
    "FOCKER 275",
    "FOCKER 275SS",
    "FOCKER 280 GT",
    "FOCKER 320 GT"
  ],
  "SCHAEFER": [
    "800",
    "PHANTOM 260",
    "PHANTOM 300",
    "PHANTOM 365",
    "PHANTOM 385",
    "PHANTOM 400",
    "PHANTOM 500 FLY",
    "PHANTOM 500 HT",
    "PHANTOM 620",
    "PHANTOM 620 PININFARINA"
  ],
  "CARBRASMAR": [
    "28",
    "30",
    "33",
    "340",
    "41",
    "460",
    "50",
    "550"
  ],
  "SEA-DOO": [
    "150 SPEEDSTER",
    "180 CHALLENGER SE",
    "200 SPEEDSTER",
    "210 CHALLENGER SE",
    "210 WAKE",
    "230 CHALLENGER SE",
    "230 CHALLENGER SP",
    "230 WAKE",
    "GTI SE 130",
    "GTI SE 155",
    "GTX 155",
    "GTX IS 215",
    "GTX LIMITED IS 260",
    "RXP 215",
    "RXP-X 255 RS",
    "RXT 215",
    "RXT IS 260",
    "RXT-X 260 RS",
    "WAKE 155",
    "WAKE PRO 215"
  ],
  "EVINRUDE": [
    "MOTOR DE BARCO"
  ],
  "INTERMARINE": [
    "42",
    "53",
    "55",
    "60",
    "65",
    "75",
    "85"
  ],
  "MAGNA": [
    "190",
    "215",
    "240",
    "260A",
    "260C",
    "278A",
    "278C",
    "310",
    "323",
    "M7"
  ],
  "AZIMUT": [
    "100 LEONARDO",
    "38",
    "39 EVOLUTION",
    "40",
    "40S",
    "42 EVOLUTION",
    "43",
    "43S",
    "45",
    "46 EVOLUTION",
    "47",
    "48",
    "50",
    "53",
    "54",
    "55 EVOLUTION",
    "55S",
    "58",
    "60",
    "62 EVOLUTION",
    "62S",
    "62S ITALIA",
    "64",
    "68 EVOLUTION",
    "68S",
    "70",
    "72S",
    "75",
    "78",
    "80",
    "82",
    "84",
    "85",
    "86S",
    "88",
    "95",
    "98 LEONARDO",
    "ATLANTIS 34",
    "ATLANTIS 35",
    "ATLANTIS 38",
    "ATLANTIS 40",
    "ATLANTIS 42HT",
    "ATLANTIS 44",
    "ATLANTIS 47",
    "ATLANTIS 48",
    "ATLANTIS 50",
    "ATLANTIS 50X4",
    "ATLANTIS 54",
    "ATLANTIS 55",
    "ATLANTIS 58",
    "ATLANTIS VERVE",
    "ATLANTIS VERVE OUTBOARD",
    "GRANDE 100",
    "GRANDE 105",
    "GRANDE 116",
    "GRANDE 120SL",
    "MAGELLANO 43",
    "MAGELLANO 43 HT",
    "MAGELLANO 50",
    "MAGELLANO 53",
    "MAGELLANO 74",
    "MAGELLANO 76"
  ],
  "CIMITARRA": [
    "340",
    "340 S",
    "360 FLY BRIDGE",
    "360 SOFT HARD TOP",
    "380 HARD TOP",
    "380 TARGA",
    "410 FLY BRIDGE",
    "410 HARD TOP",
    "410 TARGA",
    "500 FLY BRIDGE",
    "500 HARD TOP",
    "BELLAGIO 54",
    "CONTINENTAL 50 T",
    "PORTO CERVO 44"
  ],
  "FERRETTI": [
    "530",
    "55",
    "620",
    "64",
    "660",
    "700",
    "720",
    "750",
    "80",
    "830",
    "881",
    "881 RPH",
    "92"
  ],
  "BENETEAU": [
    "ANTARES",
    "ANTARES OUT-BOARD",
    "BARRACUDA",
    "FIGARO",
    "FIRST",
    "FLYER",
    "GRAN TURISMO",
    "OCEANIS",
    "PLATU",
    "SENSE",
    "SWIFT TRAWLER"
  ],
  "MONTE CARLO": [
    "MCY 65",
    "MCY 70",
    "MCY 76",
    "MCY 86"
  ],
  "LAGOON": [
    "380",
    "39",
    "400 S2",
    "421",
    "450",
    "52",
    "560",
    "620"
  ],
  "FISHING": [
    "190 CC",
    "23 WA",
    "240 CC",
    "265 CC",
    "265 SAINT-TROPEZ",
    "28 WA",
    "32 SAINT-TROPEZ",
    "320 CC",
    "320 CUDDY",
    "34 WA",
    "375 SOLARIUM",
    "38 CONVERTIBLE",
    "38 OPEN",
    "39 SAINT-TROPEZ",
    "40 RAPTOR"
  ],
  "REAL POWER BOATS": [
    "520 FLY",
    "CLASS 220",
    "CLASS 24",
    "CLASS 250",
    "CLASS 250 OPEN",
    "CLASS 26",
    "CLASS 26 OPEN",
    "CLASS 29",
    "CLASS 300",
    "CLASS 300 OPEN",
    "CLASS 45",
    "PRO FISH 190",
    "PRO FISH 250",
    "RACER 26",
    "TOP 320",
    "TOP 355",
    "TOP 38",
    "TOP 40",
    "TOP 41",
    "TOP 41 HT"
  ],
  "MAGNUM": [
    "20 OPEN",
    "23 OPEN",
    "29",
    "39 SPORT"
  ],
  "AGUZ": [
    "28 HT",
    "28 OPEN",
    "29",
    "37 HT",
    "37 OPEN"
  ],
  "MILLENIUM": [
    "170 OPEN",
    "195 OPEN",
    "225 CAB",
    "225 OPEN",
    "240 CAB",
    "240 OPEN",
    "240 SPORT",
    "245",
    "300 SPORT"
  ],
  "ALTERNATIVA": [
    "330 SPORT",
    "330 SR",
    "500 SPORT",
    "550 VISION",
    "630 CABIN",
    "630 VISION",
    "650 FISHING",
    "870 CABIN",
    "870 VISION",
    "MARLIN 16",
    "MARLIN 19",
    "MARLIN 22",
    "MARLIN 35"
  ],
  "BAYLINER": [
    "160BR",
    "170BR",
    "180BR",
    "190BR",
    "230BR",
    "250BR",
    "310BR SE",
    "350BR SE"
  ],
  "AQUA": [
    "420 HT"
  ],
  "MOONEN": [
    "100 RPH",
    "112",
    "124",
    "129 ALU",
    "24M MALLORCA",
    "38M",
    "42M",
    "42M DISPLACEMENT",
    "49M FAST DISPLACEMENT",
    "72",
    "82 ALU",
    "84",
    "94 ALU",
    "96 RPH",
    "97",
    "99 ALU",
    "CUSTOM 105",
    "CUSTOM 120",
    "CUSTOM 89",
    "CUSTOM 90",
    "CUSTOM 92",
    "EXPLORER"
  ],
  "AQUATERRA": [
    "HOLDER 12",
    "SKIPPER",
    "TEMPEST 160",
    "TEMPEST 190",
    "TEMPEST 240",
    "TEMPEST 270",
    "TOUR",
    "VICTORY",
    "WAICAT"
  ],
  "ARMADA": [
    "300M CABRIO",
    "380 GRANCABRIO",
    "400 GRANCOUPE",
    "440 SPORTCOUPE",
    "440 SPORTFLY"
  ],
  "ARTHMARINE": [
    "ARTH 240",
    "ARTH 255",
    "ARTH 295",
    "ARTH 330",
    "ARTH 415"
  ],
  "AXTOR MARINE": [
    "460",
    "M58"
  ],
  "AVALON": [
    "X3 ELITE"
  ],
  "BAIA": [
    "ATLANTICA 80",
    "AZZURRA 63",
    "ITALIA 70",
    "ONE HUNDRED"
  ],
  "BAJA MARINE": [
    "23 OUTLAW",
    "247 ISLANDER",
    "26 OUTLAW",
    "277 ISLANDER",
    "278 PERFORMANCE",
    "30 OUTLAW",
    "35 OUTLAW"
  ],
  "BENETTI": [
    "ADORA",
    "AMBROSIA III",
    "AMNESIA III",
    "CLASSIC 121",
    "CLASSIC SUPREME 132",
    "CRYSTAL 140",
    "DELFINO 93",
    "DIAMONDS ARE FOREVER",
    "F-125",
    "F-140",
    "GALAXY",
    "ILLUSION",
    "IMAGINATION",
    "LADY LARA",
    "LATINOU",
    "MEAMINA",
    "NATALY",
    "OCEAN PARADISE",
    "REVERIE",
    "SAI RAM",
    "SEANNA",
    "SILVER ANGEL",
    "SUNDAY",
    "TRADITION SUPREME 108",
    "VISION 145",
    "XANADU"
  ],
  "BILGIN": [
    "110 FLY",
    "110 SKY",
    "115",
    "123 FLY-BRIDGE",
    "123 SKY-LOUNGE",
    "127",
    "132",
    "145",
    "160 CLASSIC",
    "98",
    "98 PLUS"
  ],
  "BMYD": [
    "19 OPEN",
    "FANTASY 19",
    "FANTASY 31"
  ],
  "BRASBOATS": [
    "FLY FISH 170",
    "FLY FISH 190",
    "FLY FISH 210",
    "FLY FISH 230",
    "FLY FISH 290",
    "VOYAGER"
  ],
  "BRAVA YACHTS": [
    "308 R",
    "353 R",
    "ATITUDE 8.5",
    "HFC 44",
    "SOTO 82"
  ],
  "BRAZILIAN BOAT": [
    "190 OPEN",
    "200 CR",
    "230 CABIN",
    "230 FISHING",
    "235 CR CABIN"
  ],
  "CANTIERI DI PISA": [
    "CRANCHI SMERALDO"
  ],
  "CAPRICE": [
    "16",
    "18",
    "20",
    "OPEN FISHERMAN",
    "SKIFF"
  ],
  "CENTURY": [
    "1701",
    "2001",
    "2200",
    "2201",
    "2301",
    "2600",
    "2900",
    "2901",
    "3200"
  ],
  "CHRIS CRAFT": [
    "BULLET 20",
    "CAPRI 21",
    "CARINA 21",
    "CATALINA 23",
    "CATALINA 26",
    "CATALINA 29",
    "CATALINA 29 SUN TENDER",
    "CORSAIR 22",
    "CORSAIR 25",
    "CORSAIR 28",
    "CORSAIR 32",
    "CORSAIR 36",
    "CORSAIR 36 EUROPEAN EDITION",
    "CORSAIR 36 HARD TOP",
    "LANCER 20",
    "LAUNCH 20",
    "LAUNCH 22",
    "LAUNCH 25",
    "LAUNCH 28",
    "LAUNCH 32",
    "LAUNCH 36"
  ],
  "COLUNNA": [
    "235 CABIN",
    "235 OPEN",
    "EXPERT 3",
    "JET BOAT SENNA",
    "JET BOAT XR2-S",
    "SPORT CRUISER 285",
    "SPORT CRUISER 325",
    "SPORT CRUISER 435",
    "SPORT CRUISER 435 HT"
  ],
  "CORAL": [
    "16",
    "21",
    "24",
    "27",
    "28",
    "31A",
    "31C",
    "34A",
    "34C",
    "43",
    "46"
  ],
  "CRANCHI": [
    "40 FLY",
    "43 FLY",
    "43 HT MEDITERRANEE",
    "43 OPEN MEDITARRANEE",
    "54 FLY",
    "54 HT",
    "ATLANTIQUE 50",
    "ECO TRAWLER 53 LD",
    "ENDURANCE 27",
    "ENDURANCE 30",
    "ENDURANCE 33",
    "FIFTY 6",
    "FIFTY 8 FLY",
    "FIFTY 8 HT",
    "M 38 HT",
    "M 44 HT",
    "PANAMA 24",
    "PANAMA 29",
    "PANAMA 32",
    "SIXTY 4 HT",
    "SIXTY 6 FLY",
    "ZAFFIRO 29",
    "ZAFFIRO 32"
  ],
  "CROWNLINE": [
    "18 SS",
    "185 SS",
    "19 SS",
    "19 XS",
    "195 SS",
    "21 SS",
    "215 SS",
    "235 SS",
    "236 SC",
    "255 SS",
    "264 CR",
    "265 SS",
    "266 SC",
    "275 SS",
    "280 CR",
    "285 SS",
    "286 SC",
    "305 SS",
    "325 SCR",
    "325 SS",
    "330 CR",
    "350 CR",
    "E 1 EC",
    "E 2 EC",
    "E4",
    "E6 EC"
  ],
  "LUNA": [
    "180",
    "190",
    "200",
    "240"
  ],
  "MERCURY MARINE": [
    "MOTOR DE BARCO"
  ],
  "MAGIS": [
    "265AX",
    "275CX"
  ],
  "TOP BOATS": [
    "TOP 470",
    "TOP FISH 16",
    "TOP FISH 19",
    "TOP FISH 21",
    "TOP FISH 24 WA",
    "TOP FISH 27"
  ],
  "DIAMAR": [
    "19 LEOPARDO",
    "23 TYCOON",
    "39 BULLET"
  ],
  "COBRA": [
    "230 RAZOR",
    "230 VIPER",
    "260C VENOM",
    "27 PYTHON"
  ],
  "BATE VENTO": [
    "BV 26",
    "BV 36",
    "BV 40",
    "BV 43",
    "BV 45"
  ],
  "BERTRAM": [
    "54",
    "64",
    "70",
    "80"
  ],
  "BRAMADOR": [
    "B-24",
    "B-26",
    "B-34",
    "NOVA C"
  ],
  "BRUDDEN": [
    "EXPLORER FISHING",
    "FLYING FISHING",
    "HUNTER FISHING"
  ],
  "CARABELLI": [
    "12 FAST CRUISER",
    "28 LIFTING KEEL CRUISER",
    "30",
    "32 RIB",
    "35 RIB",
    "37 ALUMINUM CRUISER SLOOP",
    "37 IMS CRUISER-RACER",
    "395 EXPRESS",
    "44 BLUE WATER CRUISER",
    "53 PERFORMANCE CRUISER",
    "55 RAISED SALOON",
    "7 SPORTBOAT",
    "8 CLASSIC DAY SAILER",
    "ILC 25",
    "MULTIMAR 32",
    "NEO 25",
    "OPEN 40"
  ],
  "DONZI": [
    "16 CLASSIC",
    "18 CLASSIC",
    "22 CLASSIC",
    "32 ZF OPEN",
    "35 ZF OPEN",
    "35 ZFX CUDDY",
    "35 ZR",
    "35 ZR OPEN",
    "38 ZF OPEN",
    "38 ZFX CUDDY",
    "38 ZFX OPEN",
    "38 ZR",
    "38 ZSF SPORTFISH CRUISER",
    "43 ZR"
  ],
  "DELTA": [
    "36",
    "41",
    "45"
  ],
  "LEVEFORT": [
    "AMBULANCHA",
    "APOLUS",
    "CAB",
    "CARGO",
    "CATAMARA",
    "CHALANA",
    "FORTFLEX",
    "LEVEPOL",
    "MALIBU",
    "MARFIM",
    "MARUJO",
    "MAX",
    "PARATY",
    "PC",
    "SABRE",
    "SQUALUS",
    "TURISBOAT",
    "WORKBOAT"
  ],
  "NAUTIQUE": [
    "SKI 200 CB",
    "SKI 200 OB",
    "SPORT 200",
    "SUPER AIR 210",
    "SUPER AIR 230",
    "SUPER AIR G21",
    "SUPER AIR G23",
    "SUPER AIR G25"
  ],
  "EDGEWATER": [
    "145",
    "158",
    "170",
    "188",
    "188CX",
    "190IS",
    "205CX",
    "208",
    "210IS",
    "220IS",
    "228",
    "240IS",
    "245",
    "245CX",
    "268",
    "280CX",
    "318",
    "335EX",
    "388"
  ],
  "FORMULA": [
    "240 BOWRIDER",
    "240 BOWRIDER SPORT",
    "240 SUN SPORT",
    "27 PC",
    "270 BOWRIDER",
    "270 SUN SPORT",
    "290 BOWRIDER",
    "290 FX4",
    "290 FX4 BR",
    "290 SUN SPORT",
    "292 FAS3TECH",
    "31 PC",
    "310 BOWRIDER",
    "310 FX5",
    "310 FX5 BR",
    "310 SUN SPORT",
    "34 PC",
    "350 CROSSOVER BOWRIDER",
    "350 FX6",
    "350 SUN SPORT",
    "353 FAS3TECH",
    "353 FAS3TECH SPORT",
    "37 PC",
    "370 FX7",
    "370 SUPER SPORT",
    "382 FAS3TECH",
    "40 PC",
    "400 FX8",
    "400 SUPER SPORT",
    "45 YACHT"
  ],
  "HARRIS FLOTEBOTE": [
    "CROWNE 250",
    "CRUISER",
    "GRAND MARINER",
    "ROYAL",
    "SOLSTICE",
    "SUNLINER"
  ],
  "MASTERCRAFT": [
    "PROSTAR",
    "PS214V",
    "X-10",
    "X-14V",
    "X-2",
    "X-25",
    "X-30",
    "X-35",
    "X-46",
    "X-55",
    "X-STAR"
  ],
  "DOLPHIN": [
    "16 SUPER SKIFF",
    "16 SUPER SKIFF TILLER",
    "17 SUPER SKIFF",
    "18 BACKCOUNTRY PRO",
    "20 BAY BOAT",
    "RENEGADE"
  ],
  "DREAMBOATS": [
    "MV 72SOUTH",
    "MV BARBARIAN",
    "MV BREAMDREAM",
    "MV CHANCELLOR",
    "MV DREAMGENIE",
    "MV DREAMON",
    "MV PLAYTIME",
    "MV RAYDREAM",
    "MV SWEET PEA",
    "MY DREAMRAY"
  ],
  "ESQUIMAR": [
    "GERACAO I",
    "GERACAO II",
    "GERACAO III",
    "GERACAO IV"
  ],
  "EUROBOATS": [
    "200 FISHING",
    "200 OPEN",
    "230 CAB LX",
    "230 OPEN",
    "230 OPEN SPORT",
    "240 CAB LX",
    "260 CAB LX",
    "260 OPEN",
    "290 CAB LX",
    "310 CAB LX",
    "310 OPEN",
    "330 CAB LX"
  ],
  "EVOLUTION": [
    "500 CUDDY",
    "500 SANTA FE",
    "500 SPORTFISHER",
    "552 AXIS",
    "552 GOLD",
    "552 PLATINUM",
    "600 APEX EXTREME",
    "600 EXTREME",
    "650 APEX PREDATOR",
    "650 PREDATOR"
  ],
  "EVOLVE": [
    "225 CAB",
    "225 OPEN",
    "235 CAB",
    "265 CAB",
    "270 CAB"
  ],
  "FAIRLINE": [
    "SQUADRON S42",
    "SQUADRON S50",
    "SQUADRON S58",
    "SQUADRON S60",
    "SQUADRON S65",
    "SQUADRON S78",
    "TARGA T38 OPEN",
    "TARGA T44 OPEN",
    "TARGA T50 GT",
    "TARGA T58 GT"
  ],
  "SESSA MARINE": [
    "C32",
    "C35 SPORT COUPE",
    "C38",
    "C42",
    "C44",
    "C48",
    "C54 SPORTS COUPE",
    "C68",
    "DORADO 22",
    "DORADO 26 IN",
    "DORADO 26 OUT",
    "DORADO 36",
    "FLY 40",
    "FLY 47",
    "FLY 54",
    "KEY LARGO 20",
    "KEY LARGO 22",
    "KEY LARGO 24",
    "KEY LARGO 27 IN",
    "KEY LARGO 27 OUT",
    "KEY LARGO 30",
    "KEY LARGO 34 IN",
    "KEY LARGO 34 OUT",
    "KEY LARGO 36",
    "KEY LARGO ONE"
  ],
  "MIDNIGHT EXPRESS": [
    "34 OPEN",
    "34 PIED-A-MER",
    "37 CABIN",
    "37 OPEN",
    "39 CUDDY",
    "39 OPEN",
    "39 SUN LOUNGE",
    "43 OPEN"
  ],
  "STATEMENT": [
    "35",
    "38 IO",
    "38 OB",
    "42 ULTIMATE",
    "50 PASSION"
  ],
  "LUND": [
    "186 PRO-V GL",
    "186 TYEE GL",
    "197 PRO-V GL",
    "208 PRO-V GL",
    "208 TYEE GL",
    "ALASKAN",
    "BARON",
    "CROSSOVER XS",
    "FURY",
    "FURY XL",
    "IMPACT",
    "JON BOAT",
    "OUTFITTER",
    "PRO GUIDE",
    "PRO-V",
    "REBEL XL",
    "SPORT ANGLER",
    "SSV",
    "TYEE",
    "WC",
    "WD"
  ],
  "FLASH": [
    "CATFLASH35",
    "CATFLASH43",
    "FLASH135",
    "FLASH165",
    "FLASH175",
    "FLASH205",
    "OPEN590"
  ],
  "FLEXBOAT": [
    "MILITAR",
    "MINI",
    "POTRO MARINHO",
    "RAFTING",
    "SR10",
    "SR1000",
    "SR12",
    "SR15",
    "SR500",
    "SR550",
    "SR620",
    "SR760",
    "SR9.5",
    "TD10",
    "TD8"
  ],
  "FLORIDA": [
    "270 OCEAN",
    "290 SUNSET",
    "340 OCEAN",
    "360 SUNSET"
  ],
  "YANMAR": [
    "MOTOR DE BARCO"
  ],
  "FLYBOAT": [
    "FR 200",
    "FR 240",
    "FR 275",
    "FR 300",
    "FR 340",
    "FR 375",
    "FR 430",
    "FR 440",
    "FR 495",
    "NEO 25"
  ],
  "FORCE ONE": [
    "40",
    "DESTROYER"
  ],
  "FOUNTAINE PAJOT": [
    "CUMBERLAND 40 LC",
    "HELIA 44",
    "LIPARE 41 EVOLUTION",
    "MAHE 36 EVOLUTION",
    "QUEENSLAND 55",
    "SABA 50",
    "SANYA 57",
    "SUMMERLAND 40 LC",
    "TAITI DAY CHARTER 67",
    "VICTORIA 67"
  ],
  "FOUR WINNS": [
    "FUNSHIP F224",
    "FUNSHIP F244",
    "H180OBRS",
    "H180OBSS",
    "H180RS",
    "H180SS",
    "H190RS",
    "H190SS",
    "H200RS",
    "H200SS",
    "H210RS",
    "H210SS",
    "H230RS",
    "H230SS",
    "H260RS",
    "H260SS",
    "HORIZON H180",
    "HORIZON H180OB",
    "HORIZON H190",
    "HORIZON H200",
    "HORIZON H210",
    "HORIZON H230",
    "HORIZON H260",
    "HORIZON H290",
    "HORIZON H310",
    "S215RS",
    "S215SS",
    "S235RS",
    "S235SS",
    "S265RS",
    "S265SS",
    "SL222",
    "SL242",
    "SL262",
    "SUNDOWNER S215",
    "SUNDOWNER S235",
    "SUNDOWNER S265",
    "VISTA V275",
    "VISTA V305",
    "VISTA V335",
    "VISTA V355",
    "VISTA V375",
    "VISTA V435",
    "VISTA V475"
  ],
  "FS YACHTS": [
    "FS180",
    "FS205",
    "FS215",
    "FS230 SCAPPARE",
    "FS230 SIRENA",
    "FS275 CONCEPT",
    "FS305 ELITE"
  ],
  "FUTURA": [
    "ASTONDOA 40 OPEN",
    "ASTONDOA 43 OPEN HT",
    "ASTONDOA 44 FLY",
    "ASTONDOA 53 OPEN HT",
    "ASTONDOA 55 OPEN CRUISER",
    "ASTONDOA 67 OPEN",
    "ASTONDOA 72 GLX"
  ],
  "GAMPER": [
    "420",
    "450 OPEN",
    "450 PRO",
    "500",
    "600",
    "ETNA 25",
    "PILOT"
  ],
  "GENESIS": [
    "500",
    "520",
    "550",
    "580",
    "610XL",
    "640XL",
    "670XL",
    "700XL",
    "750XL",
    "800XL",
    "850XL",
    "900XL",
    "950XL HARDTOP"
  ],
  "GIANETTI": [
    "45 SPORT",
    "48 SPORT",
    "48HT",
    "55 SPORT",
    "58HT",
    "68HT",
    "NAVETTA 19",
    "NAVETTA 21",
    "NAVETTA 23",
    "NAVETTA 26",
    "NAVETTA 26 SPORT"
  ],
  "JEANNEAU": [
    "53",
    "57",
    "64",
    "CAP CAMARAT 4.7 CC",
    "CAP CAMARAT 5.1 CC",
    "CAP CAMARAT 5.5 CC SERIE 2",
    "CAP CAMARAT 5.5 WA SERIE 2",
    "CAP CAMARAT 6.5 CC SERIE 2",
    "CAP CAMARAT 6.5DC SERIE 2",
    "CAP CAMARAT 6.5WA SERIE 2",
    "CAP CAMARAT 7.5 CC",
    "CAP CAMARAT 7.5 DC",
    "CAP CAMARAT 7.5 WA",
    "CAP CAMARAT 8.5 CC",
    "CAP CAMARAT 8.5 WA",
    "LEADER 10",
    "LEADER 38",
    "LEADER 40",
    "LEADER 8",
    "LEADER 9",
    "MERRY FISHER 595",
    "MERRY FISHER 6 MARLIN",
    "MERRY FISHER 645",
    "MERRY FISHER 695 MARLIN",
    "MERRY FISHER 755",
    "MERRY FISHER 755 MARLIN",
    "MERRY FISHER 855",
    "MERRY FISHER 855 MARLIN",
    "NC 11",
    "NC 14",
    "NC 9",
    "SUN FAST 3200",
    "SUN FAST 3600",
    "SUN ODYSSEY 331",
    "SUN ODYSSEY 349",
    "SUN ODYSSEY 379",
    "SUN ODYSSEY 409",
    "SUN ODYSSEY 41DS",
    "SUN ODYSSEY 439",
    "SUN ODYSSEY 44 DS",
    "SUN ODYSSEY 469",
    "SUN ODYSSEY 50 DS",
    "SUN ODYSSEY 509",
    "VELASCO 43"
  ],
  "PRESTIGE": [
    "400",
    "440 S",
    "450",
    "450 S",
    "500",
    "500 S",
    "550",
    "550 S",
    "620",
    "620 S",
    "750"
  ],
  "HOLOS": [
    "CANOE",
    "DINGUE",
    "EMI",
    "FINN"
  ],
  "BELASSI": [
    "B3R DYNAMIC",
    "B3R PURE",
    "B3R SPORT",
    "B3S EXTREME"
  ],
  "IMPERIO": [
    "DM 200",
    "DM 280",
    "DM 340"
  ],
  "INACE": [
    "AMARELLA",
    "BATAY",
    "BELEZA",
    "BEYOND",
    "BLUE DREAM",
    "BOUNDLESS",
    "BUCCANEER",
    "BUCCANEER 65",
    "BUCCANEER 65 II",
    "BUCCANEER 68",
    "CARIB QUEEN",
    "CARLA",
    "CATALONIAN SPIRIT",
    "CONTINA",
    "EMILY",
    "FAR FAR AWAY",
    "FORTALEZA",
    "IF",
    "IMPETUS",
    "JANA",
    "JOANA II",
    "LADY BJ",
    "LILLY",
    "LOVELY",
    "MULTISEA",
    "PRECIOUS ANGEL VII",
    "SILVIA'S SURPRISE",
    "SUDAMI",
    "SUNNY",
    "VERONIKA",
    "VICTORIA",
    "ZEMBRA III"
  ],
  "INTECH": [
    "IB 360 PATROL",
    "IB 360 PILOT"
  ],
  "PALMER JOHNSON": [
    "120",
    "135",
    "150",
    "170",
    "210",
    "35M SS",
    "42M SS",
    "48M SS",
    "72M SS",
    "PJ WORLD"
  ],
  "KALMAR": [
    "LOBSTER L35",
    "RUNABOUT IT22",
    "VELEIRO CLASSICO K8"
  ],
  "LENZI": [
    "THORUS 275",
    "THORUS 305",
    "THORUS 375",
    "THORUS 405"
  ],
  "LANCER": [
    "DEEP VEE",
    "HYPALON SMALL",
    "MAXI",
    "P520",
    "P600",
    "PERFORMANCE",
    "PROFESSIONAL",
    "RD550",
    "RD570",
    "RD600",
    "RL360",
    "RL440",
    "RS340",
    "RS395",
    "RU470",
    "RU540",
    "T230",
    "T280",
    "ULTRA RIB",
    "ULTRA VEE"
  ],
  "LAZZARA": [
    "BREEZE 76",
    "LMY 116",
    "LMY 64",
    "LMY 85",
    "LSX 120",
    "LSX 64",
    "LSX 78",
    "LSX 92"
  ],
  "TRIUMPH BOATS": [
    "170 CC",
    "170 DC",
    "170 SPORTSMAN SC",
    "170 SPORTSMAN TL",
    "1700 SKIFF",
    "1700 SKIFF CC",
    "186 SPORTSMAN DC",
    "186 SPORTSMAN FS",
    "186 SPORTSMAN SC",
    "186 SPORTSMAN TL",
    "190 BAY",
    "195 CC",
    "215 CC"
  ],
  "LOTHAR": [
    "L330"
  ],
  "MAESTRALE": [
    "300",
    "320 FLY"
  ],
  "MALIBU": [
    "20 MXZ",
    "20 VTX",
    "21 RIDE",
    "21 VLX",
    "22 MXZ",
    "23 LSV",
    "23 RIDE",
    "24 MXZ",
    "247 LSV",
    "RESPONSE TXI"
  ],
  "MARES": [
    "38 CENTER CONSOLE",
    "38 HIGH PERFORMANCE"
  ],
  "MARINER": [
    "COMMODORE 230"
  ],
  "MASTERBOAT": [
    "PROSKI 590",
    "WAKESTAR"
  ],
  "MAXIMA": [
    "MAX 250 FR",
    "MAX 280",
    "MAX 340",
    "MAX 380"
  ],
  "MCP YACHTS": [
    "100LE",
    "CLASSIC 76",
    "EUROPA 100",
    "GFT 85",
    "GFT 92",
    "GFT 93",
    "GFT 98",
    "GFT 98HT",
    "HEMISPHERE 140",
    "TARGET 106"
  ],
  "MERCEDES-BENZ": [
    "MOTOR DE BARCO"
  ],
  "METALGLASS": [
    "ARUAK",
    "BIG FISH",
    "CHATA",
    "GRAND FISH",
    "KARIB",
    "MG",
    "QUEST",
    "SAVAGE"
  ],
  "MJ YACHTS": [
    "MJ 34 DS LUXO",
    "MJ 38 DS LUXO",
    "MJ 38 DS STANDARD",
    "MJ 44 DS LUXO",
    "MJ 44 DS STANDARD",
    "MJ 60 DS"
  ],
  "MOCHI CRAFT": [
    "DOLPHIN 44",
    "DOLPHIN 54",
    "DOLPHIN 64 CRUISER",
    "DOLPHIN 74 CRUISER"
  ],
  "MONTEREY": [
    "184FS",
    "186MS",
    "196MS",
    "197FS",
    "204FS",
    "204FSX",
    "214SS",
    "217 BLACKFIN",
    "224FS",
    "224FSC",
    "224FSX",
    "234SS",
    "244FS",
    "244FSX",
    "264FS",
    "264FSC",
    "264FSX",
    "268SS",
    "275SY",
    "288SS",
    "295SY",
    "315SY",
    "328SS",
    "335SY",
    "355SY",
    "415SY",
    "M3",
    "M3-MSX",
    "M5",
    "M5-MSX"
  ],
  "MOOMBA": [
    "MOBIUS LSV",
    "MOJO",
    "MONDO",
    "OUTBACK V"
  ],
  "MWM": [
    "MOTOR DE BARCO"
  ],
  "NAUTIFLEX": [
    "200",
    "240",
    "310",
    "360",
    "380",
    "430",
    "550",
    "660",
    "CLASSE I",
    "CLASSE II",
    "CLASSE III",
    "TECNOFLEX 940"
  ],
  "PAPA E PALAZZINI": [
    "20 UB CLASSIC",
    "21 SPORT CLASSIC",
    "26",
    "27"
  ],
  "PERI YACHTS": [
    "29",
    "34",
    "37",
    "41"
  ],
  "PERSHING": [
    "108",
    "115",
    "50.1 LA",
    "50.1 SD",
    "62",
    "64",
    "74",
    "82",
    "92"
  ],
  "PHANTOM": [
    "30 SPEEDSTER",
    "30 SPORTSTER",
    "30 SPORTSTER OB",
    "34 CLASSIC",
    "34 OPEN FISHERMAN",
    "40 ENFORCER",
    "45 CENTER CONSOLE",
    "45 OCEAN FISHERMAN"
  ],
  "PHOENIX": [
    "230 CLASSIC",
    "230 PLUS",
    "235 PLATINUM",
    "255 PLATINUM",
    "255 PLATINUM CENTRO",
    "275 LIMITED",
    "275 PLATINUM",
    "290 FULL",
    "290 LIMITED",
    "290 PLATINUM",
    "290 PLATINUM OPEN",
    "350 OPEN",
    "360 FULL",
    "360 LIMITED",
    "360 PLATINUM",
    "I90 PLUS",
    "I95 PLATINUM"
  ],
  "POLARIS BOATS": [
    "CONTENDER",
    "NEPTUNE",
    "RIVERMASTER",
    "RIVERRUNNER",
    "SEAMASTER",
    "SPIRIT",
    "TENDER"
  ],
  "PRINCESS": [
    "32M",
    "35M",
    "40M",
    "43",
    "52",
    "56",
    "60",
    "64",
    "72",
    "82",
    "88",
    "98",
    "S72",
    "V39",
    "V42",
    "V45",
    "V48",
    "V48 OPEN",
    "V52",
    "V57",
    "V62-S",
    "V72",
    "V78",
    "V85-S"
  ],
  "PROMAR": [
    "445",
    "520",
    "620",
    "700",
    "RAPOSO 520"
  ],
  "PSARI": [
    "170",
    "195",
    "215"
  ],
  "RANGER": [
    "ANGLER",
    "BAY",
    "FISHERMAN",
    "INTRACOASTAL",
    "INTRACOASTAL Z211",
    "REATA",
    "SKIFF 168",
    "Z COMANCHE",
    "Z100"
  ],
  "RECON": [
    "CATAMARA 26",
    "CATAMARA 43",
    "MONOCASCO 41"
  ],
  "REGAL": [
    "24 FASDECK",
    "24 FASDECK RX",
    "27 FASDECK",
    "27 FASDECK RX",
    "28 EXPRESS",
    "30 EXPRESS",
    "32 EXPRESS",
    "35 SPORT COUPE",
    "38 EXPRESS",
    "42 SPORT COUPE",
    "46 SPORT COUPE",
    "53 SPORT COUPE",
    "BOWRIDER 1900",
    "BOWRIDER 1900 ES",
    "BOWRIDER 2000",
    "BOWRIDER 2100",
    "BOWRIDER 2100 RX",
    "BOWRIDER 2300",
    "BOWRIDER 2300 RX",
    "BOWRIDER 2500",
    "BOWRIDER 2700",
    "BOWRIDER 2700 ES",
    "BOWRIDER 3200",
    "CUDDY 2250",
    "CUDDY 2550",
    "CUDDY 3550"
  ],
  "RIOSTAR": [
    "120 PROCION",
    "28 HYDRA",
    "37 GEMINI",
    "40 ALTAIR",
    "40SC ANTARES",
    "42 POLARIS",
    "45 CANOPUS",
    "49 ELECTRA",
    "51 SIRIUS",
    "55 POLLUX",
    "62 SIGNUS",
    "82 PEGASUS"
  ],
  "RIVA": [
    "122 MYTHOS",
    "56 SPORTRIVA",
    "63 VERTIGO",
    "63 VIRTUS",
    "68 EGO SUPER",
    "75 VENERE SUPER",
    "86 DOMINO",
    "92 DUCHESSA",
    "AQUARIVA SUPER",
    "ISEO",
    "RIVALE",
    "RIVARAMA SUPER"
  ],
  "RIVAL": [
    "415 OPEN",
    "430 OPEN",
    "430 SILVER FISH",
    "430SB",
    "440",
    "490 GOLDFISH",
    "490 OPEN",
    "505",
    "505W",
    "ASTRA",
    "RIB"
  ],
  "ROYAL MARINER": [
    "RM240",
    "RM270",
    "RM330",
    "RM370"
  ],
  "RUNNER": [
    "260",
    "290",
    "330",
    "335",
    "380",
    "410",
    "470",
    "500",
    "5000",
    "5500",
    "6000"
  ],
  "SAGA": [
    "310 OPEN",
    "315",
    "320 SUNTOP",
    "325",
    "365",
    "415"
  ],
  "SAIL MASTER": [
    "SR 10",
    "SR 14",
    "SR 4,2",
    "SR 5",
    "SR 6,3",
    "SR 8"
  ],
  "SAPPHIRE": [
    "13 SPEED BOAT",
    "ZAPPHIRA 55"
  ],
  "SEA CREST": [
    "ADVENTURE 215",
    "ADVENTURE 250 CABIN",
    "ADVENTURE 290 CRUISER",
    "FISHING 150",
    "FISHING 185",
    "FISHING 215",
    "FISHING 245",
    "FISHING 280 CABIN",
    "FISHING 280 OPEN",
    "FISHING 320 CABIN",
    "FISHING 320 OPEN",
    "FISHING 360 CABIN"
  ],
  "SEA RAY": [
    "190 SPORT",
    "205 SPORT",
    "210 SLX",
    "210 SUN SPORT",
    "220 SUNDECK",
    "220 SUNDECK OB",
    "230 SLX",
    "240 SUN SPORT",
    "240 SUNDECK",
    "240 SUNDECK OB",
    "250 SLX",
    "260 SUNDANCER",
    "260 SUNDECK",
    "265 SUNDANCER",
    "270 SLX",
    "280 SUNDANCER",
    "280 SUNDECK",
    "300 SLX",
    "300 SUNDECK",
    "305 SUNDANCER",
    "310 SUNDANCER",
    "330 SUNDANCER",
    "350 SLX",
    "350 SUNDANCER",
    "355 SUNDANCER",
    "370 SUNDANCER",
    "370 VENTURE",
    "410 SUNDANCER",
    "450 SEDAN BRIDGE",
    "450 SUNDANCER",
    "470 SUNDANCER",
    "510 FLY",
    "510 SUNDANCER",
    "540 SUNDANCER"
  ],
  "SEA HAWK": [
    "ISLAND HOPPER 30",
    "PRO 45",
    "PRO 51",
    "SEA HAWK 36"
  ],
  "SEGUE YACHTS": [
    "32 OPEN",
    "40 CUSTON",
    "42V",
    "45 HT",
    "48 FLY",
    "55 FLY",
    "58 HT",
    "72",
    "86 MY",
    "94"
  ],
  "SILVERTON": [
    "33 CONVERTIBLE",
    "33 SPORT COUPE",
    "35 MOTOR YACHT",
    "36 CONVERTIBLE",
    "38 CONVERTIBLE",
    "38 SPORT BRIDGE",
    "39 MOTOR YACHT",
    "42 CONVERTIBLE",
    "43 SPORT BRIDGE",
    "45 CONVERTIBLE",
    "45 T-SERIES",
    "50 CONVERTIBLE",
    "50 T-SERIES"
  ],
  "SKIPPER": [
    "115",
    "4U",
    "680",
    "780",
    "95"
  ],
  "STERLING": [
    "ATLANTIC 41",
    "ATLANTIC 43",
    "ATLANTIC 45",
    "ATLANTIC 53",
    "LEGEND 28"
  ],
  "STRIDER": [
    "170",
    "250"
  ],
  "SUNFLASH": [
    "17",
    "230",
    "26"
  ],
  "SUNLINE": [
    "315",
    "FLORIPA 160",
    "FLORIPA 190"
  ],
  "SUNSEEKER": [
    "101 SPORT YACHT",
    "115 SPORT YACHT",
    "130 SPORT YACHT",
    "155 YACHT",
    "28 METRE YACHT",
    "34 METRE YACHT",
    "40 METRE YACHT",
    "68 SPORT YACHT",
    "75 YACHT",
    "80 SPORT YACHT",
    "80 YACHT",
    "86 YACHT",
    "88 YACHT",
    "MANHATTAN 55",
    "MANHATTAN 63",
    "MANHATTAN 73",
    "PORTOFINO 40",
    "PREDATOR 53",
    "PREDATOR 60",
    "PREDATOR 68",
    "PREDATOR 80",
    "PREDATOR 84",
    "SAN REMO"
  ],
  "SUPERBOATS": [
    "CAT45",
    "V38",
    "V40",
    "V42 DAYCRUISER",
    "V52"
  ],
  "SUPRA": [
    "LAUNCH 242",
    "SA 350",
    "SA 550",
    "SC 350",
    "SC 550",
    "SUNSPORT 242"
  ],
  "TECNOBOATS": [
    "26",
    "28",
    "285 NOBLE",
    "29",
    "305",
    "32",
    "330",
    "MIAMI FISHING"
  ],
  "TEMPEST": [
    "165",
    "166",
    "172",
    "175",
    "192",
    "CHARGER PICKLEFORK",
    "CHARGER STV"
  ],
  "TOHATSU": [
    "MOTOR DE BARCO"
  ],
  "TRITON": [
    "200 CAB",
    "200 OPEN",
    "240 CAB",
    "240 OPEN",
    "260",
    "295",
    "345",
    "345 HT",
    "365",
    "I275"
  ],
  "VEGA": [
    "230 CLASSIC",
    "290 CLASSIC",
    "350 CLASSIC",
    "460 CLASSIC"
  ],
  "VICTORY YACHTS": [
    "245",
    "260",
    "300",
    "315"
  ],
  "VOLVO": [
    "MOTOR DE BARCO"
  ],
  "WELLCRAFT": [
    "180 FISHERMAN",
    "180 SPORTSMAN",
    "210 COASTAL",
    "210 FISHERMAN",
    "210 SPORTSMAN",
    "232 COASTAL",
    "232 FISHERMAN",
    "252 COASTAL",
    "252 FISHERMAN",
    "290 COASTAL",
    "30 SPORT",
    "30 TOURNAMENT",
    "340 COASTAL",
    "35 SPORT",
    "35 TOURNAMENT"
  ],
  "YACXO": [
    "307",
    "357 HT",
    "357 SC"
  ],
  "ZODIAC": [
    "BAYRUNNER 310",
    "BAYRUNNER 340",
    "BAYRUNNER 420",
    "BAYRUNNER 500",
    "BAYRUNNER 550",
    "BAYRUNNER 650",
    "CADET 200 ROLL UP",
    "CADET 240 AERO",
    "CADET 240 ROLL UP",
    "CADET 260 AERO",
    "CADET 260 ROLL UP",
    "CADET 260 SOLID",
    "CADET 285 SOLID",
    "CADET 310 SOLID",
    "CADET 340 SOLID",
    "CADET COMPACT 250",
    "CADET COMPACT 250 NEO",
    "CADET COMPACT 300",
    "CADET COMPACT 300 NEO",
    "CADET FASTROLLER 285",
    "CADET FASTROLLER 325",
    "CADET FASTROLLER 360",
    "CADET RIB 260",
    "CADET RIB 260 NEO",
    "CADET RIB 290",
    "CADET RIB 290 NEO",
    "CADET RIB 310",
    "CADET RIB 310 NEO",
    "CADET RIB 340",
    "CADET RIB 340 NEO",
    "CLASSIC MARK I ALU",
    "CLASSIC MARK I SOLID",
    "CLASSIC MARK II ALU",
    "CLASSIC MARK II C SOLID",
    "CLASSIC MARK II SOLID",
    "FUTURA MARK II ALU",
    "FUTURA MARK II C ALU",
    "FUTURA MARK II C FR",
    "FUTURA MARK II FR",
    "FUTURA MARK III ALU",
    "FUTURA MARK III FR",
    "MEDLINE 500",
    "MEDLINE 540",
    "MEDLINE 580",
    "N-ZO 600",
    "N-ZO 680",
    "N-ZO 700 CABIN",
    "N-ZO 760",
    "PRO CLASSIC 420",
    "PRO CLASSIC 500",
    "PRO CLASSIC 550",
    "PRO CLASSIC 650",
    "PRO CLASSIC 750",
    "PRO OPEN 550",
    "PRO OPEN 650",
    "PRO RACING 500",
    "PRO RACING 550",
    "PRO TOURING 500",
    "PRO TOURING 550",
    "REC PRO 650",
    "YACHTLINE 340",
    "YACHTLINE 380",
    "YACHTLINE 420",
    "YACHTLINE 470",
    "ZOOM 200 ROLL UP",
    "ZOOM 230 AERO",
    "ZOOM 230 ROLL UP",
    "ZOOM 260 AERO",
    "ZOOM 260 ROLL UP",
    "ZOOM 260 SOLID",
    "ZOOM 310 SOLID",
    "ZOOM SP 350 ALU",
    "ZOOM SP 400 ALU",
    "ZOOM SP 450 ALU"
  ],
  "ZONDA": [
    "32",
    "42",
    "HPE 25"
  ],
  "FLIPPER": [
    "520 HT",
    "605 WA",
    "625 DC",
    "630 CC",
    "630 HT",
    "630 OC",
    "640 DC",
    "640 ST",
    "670 DC",
    "670 ST",
    "760 DC",
    "880 ST"
  ],
  "GALEON": [
    "290 FLY",
    "325 HTS",
    "325 OPEN",
    "340 FLY",
    "350 HTC",
    "380 FLY",
    "385 HTL",
    "385 HTS",
    "385 OPEN",
    "390 HTC",
    "420 FLY",
    "430 HTC",
    "430 SKYDECK",
    "445 HTS",
    "550 FLY",
    "560 SKYDECK",
    "640 FLY",
    "700 RAPTOR",
    "700 SKYDECK",
    "780 CRYSTAL",
    "820 SKYDECK"
  ],
  "HEESEN": [
    "37M",
    "40M",
    "42M",
    "44M",
    "45M",
    "47M",
    "50M",
    "51M",
    "55M",
    "65M"
  ],
  "KRAUSE": [
    "160",
    "195",
    "235",
    "TR 16",
    "TR 16 SPORT",
    "TR 21"
  ],
  "SUNREEF": [
    "210 POWER TRIMARAN",
    "58",
    "60",
    "60 POWER",
    "70",
    "70 POWER",
    "75 SPORTFISH",
    "80",
    "82",
    "90 POWER",
    "DOUBLE DECK",
    "SINGLE DECK",
    "ULTIMATE"
  ]
};

export function getBrandsByCategory(category: VehicleCategory = 'MOTO'): string[] {
  if (category === 'MOTO') return MOTO_BRANDS;
  if (category === 'NAUTICA') return NAUTICA_BRANDS;
  return ALL_BRANDS;
}

export function getModelsByBrand(brand: string): string[] {
  if (!brand) return [];
  const upper = brand.toUpperCase().trim();
  if (BRAND_MODELS_MAP[upper]) {
    return BRAND_MODELS_MAP[upper];
  }
  const key = Object.keys(BRAND_MODELS_MAP).find(k => k.toUpperCase() === upper);
  if (key) {
    return BRAND_MODELS_MAP[key];
  }
  return [];
}
